### staging dataset

In [1]:
from google.cloud import bigquery

project_id = "segfault-434120"
dataset = "skincare_products_stg"
region = "us-central1"

bq_client = bigquery.Client()

dataset_id = bigquery.Dataset(f"{project_id}.{dataset}")
dataset_id.location = region
resp = bq_client.create_dataset(dataset_id, exists_ok=True)
print("Created dataset {}.{}".format(bq_client.project, resp.dataset_id))

Created dataset segfault-434120.skincare_products_stg

In [ ]:
!pip install vertexai

### `cosmetic_ingredient` table

##### Replace empty or empty string equivalents with null

In [2]:
%%bigquery
select
  case cosing_ref_no when '' then null else cosing_ref_no end as cosing_ref_no,
  case ingredient_unique_name when '' then null else ingredient_unique_name end as ingredient_unique_name,
  case ingredient_common_name when '' then null else ingredient_common_name end as ingredient_common_name,
  case european_pharmacopoeia_name when '' then null else european_pharmacopoeia_name end as european_pharmacopoeia_name,
  case
    when cas_no in (' ', ' -') then null
    else cas_no
  end as cas_no,
  case
    when ec_no in (' ', ' ,', ' -', ' - ', ' - / -') then null
    else ec_no
  end as ec_no,
  case restriction when '' then null else restriction end as restriction,
  case function when '' then null else function end as function,
  case update_date when '' then null else update_date end as update_date,
from skincare_products_raw.cosmetic_ingredient;

Query is running:   0%|          |

Downloading:   0%|          |

,cosing_ref_no,ingredient_unique_name,ingredient_common_name,european_pharmacopoeia_name,cas_no,ec_no,restriction,function,update_date
0,None,None,None,None,None,None,None,None,None
1,92615,BIORESMETHRIN,None,None,28434-01-7,249-014-0 (I),None,None,21/07/2015
2,89117,CAPRYLYL LAURATE,None,None,5303-24-2,226-149-3,None,None,24/07/2012
3,88730,CARRAGEENAN,None,None,9000-07-1,232-524-2 (I),None,None,24/07/2012
4,89008,CITRUS AURANTIUM BERGAMIA PEEL OIL,None,None,89957-91-5,289-612-9,None,None,25/07/2012
...,...,...,...,...,...,...,...,...,...
28709,60168,WHEAT GERM OIL PEG-8 ESTERS,None,None,None,None,None,"SKIN CONDITIONING, SKIN CONDITIONING - EMOLLIE...",15/10/2010
28710,59648,SODIUM STEAROYL HYDROLYZED SWEET ALMOND PROTEIN,None,None,None,None,None,"ANTISTATIC, SKIN CONDITIONING, SKIN CONDITIONI...",15/10/2010
28711,82225,SODIUM HYDROXYPROPYLSULFONATE DECYLGLUCOSIDE C...,None,None,None,None,None,"CLEANSING, SURFACTANT - CLEANSING, SURFACTANT ...",15/10/2010
28712,57270,PEG/PPG-70/30 TOCOPHERYL ETHER,None,None,None,None,None,"ANTICAKING, ANTIOXIDANT, BINDING, EMULSION STA...",24/01/2011
28713,57105,PEG/PPG-100/70 TOCOPHERYL ETHER,None,None,None,None,None,"ANTICAKING, ANTIOXIDANT, BINDING, EMULSION STA...",24/01/2011

#### Cast `date` from STRING to DATE

In [3]:
%%bigquery
select update_date as orig_date, safe_cast(update_date as DATE) as new_date
from skincare_products_raw.cosmetic_ingredient
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

    orig_date new_date
0        None      NaT
1  21/07/2015      NaT
2  24/07/2012      NaT
3  24/07/2012      NaT
4  25/07/2012      NaT

In [4]:
%%bigquery
select update_date as orig_date, safe_cast(update_date as DATE format 'DD/MM/YYYY') as new_date
from skincare_products_raw.cosmetic_ingredient
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

    orig_date    new_date
0        None         NaT
1  21/07/2015  2015-07-21
2  24/07/2012  2012-07-24
3  24/07/2012  2012-07-24
4  25/07/2012  2012-07-25

#### Cast `cosing_ref_no` from STRING to INTEGER

In [5]:
%%bigquery
select cosing_ref_no as orig_cosing_ref_no, safe_cast(cosing_ref_no as INTEGER) as new_cosing_ref_no
from skincare_products_raw.cosmetic_ingredient
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

  orig_cosing_ref_no  new_cosing_ref_no
0               None               <NA>
1              92615              92615
2              89117              89117
3              88730              88730
4              89008              89008

#### Rename ambiguous fields

In [6]:
%%bigquery
select
  restriction as regulatory_restriction,
  function as intended_use,
from skincare_products_raw.cosmetic_ingredient;

Query is running:   0%|          |

Downloading:   0%|          |

,regulatory_restriction,intended_use
0,None,None
1,,
2,,
3,,
4,,
...,...,...
28709,,"SKIN CONDITIONING, SKIN CONDITIONING - EMOLLIE..."
28710,,"ANTISTATIC, SKIN CONDITIONING, SKIN CONDITIONI..."
28711,,"CLEANSING, SURFACTANT - CLEANSING, SURFACTANT ..."
28712,,"ANTICAKING, ANTIOXIDANT, BINDING, EMULSION STA..."
28713,,"ANTICAKING, ANTIOXIDANT, BINDING, EMULSION STA..."

#### Putting it all together

In [7]:
%%bigquery
select
  safe_cast(cosing_ref_no as INTEGER) as cosing_ref_no,
  case ingredient_unique_name when '' then null else ingredient_unique_name end as ingredient_unique_name,
  case ingredient_common_name when '' then null else ingredient_common_name end as ingredient_common_name,
  case european_pharmacopoeia_name when '' then null else european_pharmacopoeia_name end as european_pharmacopoeia_name,
  case
    when cas_no in (' ', ' -') then null
    else cas_no
  end as cas_no,
  case
    when ec_no in (' ', ' ,', ' -', ' - ', ' - / -') then null
    else ec_no
  end as ec_no,
  case restriction when '' then null else restriction end as regulatory_restriction,
  case function when '' then null else function end as intended_use,
  case update_date when '' then null else safe_cast(update_date as DATE format 'DD/MM/YYYY') end as update_date,
from skincare_products_raw.cosmetic_ingredient;

Query is running:   0%|          |

Downloading:   0%|          |

,cosing_ref_no,ingredient_unique_name,ingredient_common_name,european_pharmacopoeia_name,cas_no,ec_no,regulatory_restriction,intended_use,update_date
0,<NA>,None,None,None,None,None,None,None,NaT
1,92615,BIORESMETHRIN,None,None,28434-01-7,249-014-0 (I),None,None,2015-07-21
2,89117,CAPRYLYL LAURATE,None,None,5303-24-2,226-149-3,None,None,2012-07-24
3,88730,CARRAGEENAN,None,None,9000-07-1,232-524-2 (I),None,None,2012-07-24
4,89008,CITRUS AURANTIUM BERGAMIA PEEL OIL,None,None,89957-91-5,289-612-9,None,None,2012-07-25
...,...,...,...,...,...,...,...,...,...
28709,60168,WHEAT GERM OIL PEG-8 ESTERS,None,None,None,None,None,"SKIN CONDITIONING, SKIN CONDITIONING - EMOLLIE...",2010-10-15
28710,59648,SODIUM STEAROYL HYDROLYZED SWEET ALMOND PROTEIN,None,None,None,None,None,"ANTISTATIC, SKIN CONDITIONING, SKIN CONDITIONI...",2010-10-15
28711,82225,SODIUM HYDROXYPROPYLSULFONATE DECYLGLUCOSIDE C...,None,None,None,None,None,"CLEANSING, SURFACTANT - CLEANSING, SURFACTANT ...",2010-10-15
28712,57270,PEG/PPG-70/30 TOCOPHERYL ETHER,None,None,None,None,None,"ANTICAKING, ANTIOXIDANT, BINDING, EMULSION STA...",2011-01-24
28713,57105,PEG/PPG-100/70 TOCOPHERYL ETHER,None,None,None,None,None,"ANTICAKING, ANTIOXIDANT, BINDING, EMULSION STA...",2011-01-24

#### Create staging table

In [9]:
%%bigquery
create or replace table skincare_products_stg.cosmetic_ingredient as
  select
  safe_cast(cosing_ref_no as INTEGER) as cosing_ref_no,
  case ingredient_unique_name when '' then null else ingredient_unique_name end as ingredient_unique_name,
  case ingredient_common_name when '' then null else ingredient_common_name end as ingredient_common_name,
  case european_pharmacopoeia_name when '' then null else european_pharmacopoeia_name end as european_pharmacopoeia_name,
  case
    when cas_no in (' ', ' -') then null
    else cas_no
  end as cas_no,
  case
    when ec_no in (' ', ' ,', ' -', ' - ', ' - / -') then null
    else ec_no
  end as ec_no,
  case restriction when '' then null else restriction end as regulatory_restriction,
  case function when '' then null else function end as intended_use,
  case update_date when '' then null else safe_cast(update_date as DATE format 'DD/MM/YYYY') end as update_date,
  _data_source,
   _load_time
  from skincare_products_raw.cosmetic_ingredient;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

### `dermatologic_disease` table

#### Create staging table and format `treatments` into string list using LLM

In [108]:
import vertexai
from vertexai.generative_models import GenerativeModel, Part, HarmCategory, HarmBlockThreshold
from google.cloud import bigquery
import pandas as pd
import json
from pandas_gbq import read_gbq, to_gbq

# Initialize Vertex AI
project_id = "segfault-434120"
region = "us-central1"
model_name = "gemini-1.5-flash-001"
vertexai.init(project=project_id, location=region)
model = GenerativeModel(model_name)

# Initialize BigQuery client
bq_client = bigquery.Client()

# SQL query to pull treatments column from BigQuery
query = """select * from skincare_products_raw.dermatologic_disease"""

# Prompt for Vertex AI
prompt = """Go through this treatment string and look for ingredient-based treatments only.
Ingredient-based treatments are those which refer specifically to substances or compounds used in the treatment, such as "minocycline", "aloe", "vitamin E", or "salicylic acid".
Do not include general treatments like "surgery", "physical therapy", or "laser treatment".
Add only ingredient-based treatments into a list.
For example, if "minocycline", "aloe", "warm compresses", and "surgery" are included in the given set of treatments, create a list with "minocycline" and "aloe".
Do not include the others.

Return the original treatment string along with the list of ingredient-based treatments you extracted.
Format the results as JSON with the schema: original_treatments:string, ingredient_treatments:array<string>.
Do not include an explanation in your response.
"""

# Function to process treatment using Vertex AI
def process_treatment(treatment):
  try:
    resp = model.generate_content(contents=[treatment, prompt], safety_settings={
                HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
            })
    resp_text = resp.text.replace("```json", "").replace("```", "").replace("\n", "")
    return json.loads(resp_text)
  except:
    return {  "original_treatments": treatment,  "ingredient_treatments": []}

# Fetch data from BigQuery
# rows = bq_client.query(treatments_query).to_dataframe()
rows = read_gbq(query, project_id=project_id)

# Process the treatments column only if it is non-null
processed_treatments = []
for index, row in rows.iterrows():
    treatment_string = row["treatments"]

    if pd.notnull(treatment_string):
      processed = process_treatment(treatment_string)
      print(processed)
      # Update the treatments column with the processed ingredient list (as JSON string)
      rows.at[index, "treatments"] = json.dumps(processed["ingredient_treatments"])

# Load the transformed data back into BigQuery using pandas-gbq
table_id = f"{project_id}.skincare_products_stg.dermatologic_disease"
to_gbq(rows, table_id, project_id=project_id, if_exists='replace')

Downloading: 100%|██████████|
{'original_treatments': 'Cocoa butter, shea butter, vitamin E, gotu kola extract, hyaluronic acid, elastin, egg oil, wheat germ oil, retinoids, vitamin C, alpha hydroxy acids (glycolic, lactic, citric, tartaric, and malic acids),  trichloroacetic acid (TCA), and microdermabrasion.', 'ingredient_treatments': ['Cocoa butter', 'shea butter', 'vitamin E', 'gotu kola extract', 'hyaluronic acid', 'elastin', 'egg oil', 'wheat germ oil', 'retinoids', 'vitamin C', 'glycolic acid', 'lactic acid', 'citric acid', 'tartaric acid', 'malic acid', 'trichloroacetic acid (TCA)']}
{'original_treatments': 'The main treatment focuses on preventing the wet-to-dry cycles. This involves wearing breathable footwear, thicker absorbent socks, and avoiding rapid drying of the feet. An occlusive, soothing ointment is applied to the affected areas to prevent drying out.', 'ingredient_treatments': []}
{'original_treatments': 'Surgical excision is the most common treatment for moles. Smaller moles can be shaved off, while larger moles may be cut out directly and the wound edges sewn together.  Laser treatment, chemical peels and dermabrasion can also be used to destroy nevus cells.', 'ingredient_treatments': []}
{'original_treatments': 'null', 'ingredient_treatments': []}
{'original_treatments': 'null', 'ingredient_treatments': []}
{'original_treatments': 'null', 'ingredient_treatments': []}
{'original_treatments': 'null', 'ingredient_treatments': []}
{'original_treatments': 'null', 'ingredient_treatments': []}
{'original_treatments': 'null', 'ingredient_treatments': []}
{'original_treatments': 'null', 'ingredient_treatments': []}
{'original_treatments': 'null', 'ingredient_treatments': []}
{'original_treatments': 'null', 'ingredient_treatments': []}
{'original_treatments': 'Capsaicin cream, pramoxine cream, doxepin cream, amitriptyline 1%/ketamine 0.5% cream, ice packs, gabapentin, lamotrigine, carbamazepine, valproate, oral antihistamines, physical therapy, cervical traction devices, acupuncture, osteopathic manipulative therapy', 'ingredient_treatments': ['Capsaicin', 'pramoxine', 'doxepin', 'amitriptyline', 'ketamine', 'gabapentin', 'lamotrigine', 'carbamazepine', 'valproate']}
{'original_treatments': 'Pain relievers, cool compresses to dry blisters, antiviral pills (Famvir, Zovirax, Valtrex), or other medications (Neurontin, Tegretol, Elavil) to treat pain. Injections of cortisone, especially directly into the area of nerve pain, can also help ease the pain.', 'ingredient_treatments': ['Famvir', 'Zovirax', 'Valtrex', 'Neurontin', 'Tegretol', 'Elavil', 'cortisone']}
{'original_treatments': 'Treatments aim to restore pigment by promoting the growth of new melanocytes. Treatments include topical ruxolitinib cream, pimecrolimus cream, tacrolimus ointment, narrow-band UVB light therapy, surgical skin grafts, camouflage makeup, and depigmentation therapy.', 'ingredient_treatments': ['ruxolitinib', 'pimecrolimus', 'tacrolimus']}
{'original_treatments': 'Avoid friction and sweating, use sunscreen, apply soothing compresses, use topical corticosteroids and antibiotics, oral antibiotics, oral corticosteroids, dapsone, topical tacrolimus, photodynamic therapy, dermabrasion, laser treatment, and surgical skin grafting.', 'ingredient_treatments': ['sunscreen', 'corticosteroids', 'antibiotics', 'dapsone', 'tacrolimus']}
{'original_treatments': 'Antibiotics, topical corticosteroids, oral corticosteroids, light therapy, surgery, photodynamic therapy, cryotherapy, retinoids, salicylic acid, benzoyl peroxide, laser treatment, chemical peels, antibiotics, topical antibiotics, oral antibiotics, azelaic acid, clindamycin, erythromycin, doxycycline, tetracycline, minocycline, topical corticosteroids, oral corticosteroids, hydrocortisone, prednisone, methylprednisolone,  light therapy, blue light therapy, red light therapy,  surgery, photodynamic therapy, cryotherapy, retinoids, tretinoin, adapalene, tazarotene, salicylic acid, benzoyl peroxide, laser treatment, chemical peels, antibiotics, topical antibiotics, oral antibiotics, azelaic acid, clindamycin, erythromycin, doxycycline, tetracycline, minocycline', 'ingredient_treatments': ['minocycline', 'salicylic acid', 'benzoyl peroxide', 'azelaic acid', 'clindamycin', 'erythromycin', 'doxycycline', 'tetracycline', 'hydrocortisone', 'prednisone', 'methylprednisolone', 'tretinoin', 'adapalene', 'tazarotene']}
{'original_treatments': 'Treatment focuses on managing symptoms, primarily with topical steroids, clindamycin, pimecrolimus, and tacrolimus.  Other treatments may include oral contraceptives, laser therapy, botulinum toxin injections, or removal of apocrine glands. There is currently no cure.', 'ingredient_treatments': ['clindamycin', 'pimecrolimus', 'tacrolimus', 'botulinum toxin']}
{'original_treatments': 'Treatment primarily involves removing the irritant by washing the affected area with soap and water. Cool wet soaks and strong topical steroid application are also recommended. In some cases, oral ciprofloxacin may be prescribed to address potential bacterial infection.', 'ingredient_treatments': ['ciprofloxacin']}
{'original_treatments': 'Treatment for PN is challenging. It typically involves a combination of therapies, including: potent prescription steroid creams, milder steroid creams for long-term control, antihistamine creams (Zonalon, Pramoxine) or pills (Atarax, Periactin), intralesional steroid injections, anti-depressant pills, non-prescription capsaicin cream, and in severe cases, cryotherapy (freezing with liquid nitrogen spray), oral steroids, or PUVA (psoralen and ultraviolet A radiation). It is crucial to avoid scratching the affected areas.', 'ingredient_treatments': ['psoralen', 'capasaicin']}
{'original_treatments': 'Treatments for psoriasis include topical therapies like moisturizers, steroids, non-steroid treatments, salicylic or lactic acids, and dandruff shampoos. Systemic treatments include oral medications like methotrexate, acitretin, and cyclosporine, and injectable medicines such as adalimumab, etanercept, infliximab, and ustekinumab. Phototherapy, using UVA and UVB light, is another treatment option. Vitamin-D analog containing ointments, such as calcipotriene and calcitriol, are also used to reduce the thickness of scales.', 'ingredient_treatments': ['methotrexate', 'acitretin', 'cyclosporine', 'adalimumab', 'etanercept', 'infliximab', 'ustekinumab', 'calcipotriene', 'calcitriol', 'salicylic acid', 'lactic acid']}
{'original_treatments': 'Potassium Iodide', 'ingredient_treatments': ['Potassium Iodide']}
{'original_treatments': 'Excisional biopsy to completely remove the lesion. For sensitive areas, Mohs micrographic surgery can be used to spare as much tissue as possible. If surgery is not possible, topical imiquimod, intralesional interferon-alfa, radiation therapy or laser therapy may be used.', 'ingredient_treatments': ['imiquimod', 'interferon-alfa']}
{'original_treatments': 'Treatment may involve removing the flea with a sterile needle or using medications to alleviate symptoms. In severe cases, surgery may be necessary. To prevent infection, it is recommended to cover your feet and avoid contact with sand in areas known to have jigger fleas.', 'ingredient_treatments': []}
{'original_treatments': 'Calcium channel blockers, muscle relaxants, phenoxybenzamine (an alpha adrenergic blocker) and gabapentin. Surgical excision is a possible solution, but recurrence after surgery is common.  Botulinum toxin and carbon dioxide laser ablation are currently being investigated.', 'ingredient_treatments': ['calcium channel blockers', 'muscle relaxants', 'phenoxybenzamine', 'gabapentin', 'botulinum toxin']}
{'original_treatments': 'Moisturizer creams or lotions are recommended to retain moisture, and a low potency topical corticosteroid can be prescribed to reduce inflammation and symptoms. A nonsteroidal topical cream, such as Elidel, can also reduce itching and redness for those over the age of two.', 'ingredient_treatments': ['corticosteroid']}
{'original_treatments': 'Sun protection with broad-spectrum sunscreen, and protective clothing. Topical or intralesional corticosteroids, antimalarials like hydroxychloroquine, dapsone, thalidomide, interferon, systemic retinoids, and immunosuppressive agents. Vitamin D and calcium supplementation.', 'ingredient_treatments': ['hydroxychloroquine', 'dapsone', 'thalidomide', 'interferon', 'retinoids', 'vitamin D', 'calcium']}
{'original_treatments': 'Treatment involves discontinuing the use of topical corticosteroids. Mild cases respond well to antifungal creams, while more severe cases may require oral medications such as terbinafine and fluconazole. If the lesion is infected with bacteria, antibiotics may be necessary.', 'ingredient_treatments': ['terbinafine', 'fluconazole']}
{'original_treatments': 'Treatment involves immediately moving the affected person to a warm location, removing wet clothing and constricting items, and immersing the affected area in warm water (98.6-102.2 degrees Fahrenheit) for 15-30 minutes until the tissue feels soft and appears red or purple. Avoid rubbing the affected area as this can cause further damage.  Rewarming should not occur if there is a chance of refreezing, which can worsen the injury. Seek medical attention for further treatment, which may include specialized treatment or surgery.', 'ingredient_treatments': []}
{'original_treatments': 'Removal of the offending heat source. Mild cases will resolve over time, while more advanced cases may require treatment with 5-fluorouracil, tretinoin, or laser therapy. In rare cases, cancer can develop from Erythema ab igne, so monitoring and possible biopsy are recommended.', 'ingredient_treatments': ['5-fluorouracil', 'tretinoin']}
{'original_treatments': 'The primary treatment is to remove the underlying cause. If a cause is not identified, treatments may include non-steroidal anti-inflammatory drugs (NSAIDs), bed rest, and injections. Potassium iodide is a strong but unpleasant treatment that can help reduce pain and swelling.', 'ingredient_treatments': ['Potassium iodide']}
{'original_treatments': 'Treatment options include topical steroid ointments, tar solution soaks, Tazorac or Dovonex ointments, ultraviolet light therapy (with or without oral medications), oral medications like Soriatane, Cyclosporin or Methotrexate, and occasionally colchicine, tetracycline or dapsone.', 'ingredient_treatments': ['colchicine', 'tetracycline', 'dapsone']}
{'original_treatments': 'Weight loss, avoiding tight clothing, lidocaine/methylprednisolone injections, botulinum toxin injections, pulse radio frequency, spinal cord stimulation, capsaicin cream, lidocaine patches, tricyclic antidepressants, gabapentin, physical therapy, Kinesio Taping, and acupuncture.', 'ingredient_treatments': ['lidocaine', 'methylprednisolone', 'botulinum toxin', 'capsaicin', 'lidocaine', 'tricyclic antidepressants', 'gabapentin']}
{'original_treatments': 'Treatment typically focuses on increasing blood flow to the heart. This can involve elevating the extremities, support stockings, and regular walking to encourage blood flow. If necessary, medicated creams, topical corticosteroids, or pentoxifylline may be used to treat skin irritation or ulcers.  Antibiotics may be prescribed for infections. If the condition is severe, a vascular surgeon might be needed to operate on the veins.  In cases of significant leg swelling, underlying conditions like heart failure should be investigated.', 'ingredient_treatments': ['pentoxifylline', 'topical corticosteroids']}
{'original_treatments': 'Hormone replacement therapy', 'ingredient_treatments': []}
{'original_treatments': 'Ivermectin, malathion lotion', 'ingredient_treatments': ['ivermectin', 'malathion']}
{'original_treatments': 'Zinc sulfate supplementation', 'ingredient_treatments': ['zinc sulfate']}
{'original_treatments': 'Treatment varies depending on the severity of the condition.  In mild cases, the offending agent may need to be identified and removed. In more severe cases, systemic corticosteroids and immunosuppressive agents may be necessary. Colchicine and dapsone may also be helpful in some cases.', 'ingredient_treatments': ['colchicine', 'dapsone', 'systemic corticosteroids', 'immunosuppressive agents']}
{'original_treatments': 'Punch excision or shave excision.', 'ingredient_treatments': []}
{'original_treatments': 'Accutane, Soriatane, or methotrexate', 'ingredient_treatments': ['Accutane', 'Soriatane', 'methotrexate']}
{'original_treatments': 'Dapsone, sulfapyridine, tetracycline', 'ingredient_treatments': ['Dapsone', 'sulfapyridine', 'tetracycline']}
{'original_treatments': 'Treatment depends on the type, location, and risk of the SCC. Options include excision (cutting out the SCC), cryosurgery (freezing), electrodesiccation and curettage (scraping and cauterizing), Mohs surgery (a specialized microscopically controlled surgical technique), and radiation therapy.', 'ingredient_treatments': []}
{'original_treatments': 'Treated with biologic medications that target specific molecules within the immune system, reducing inflammation and slowing cell growth.  Biologics may be administered intravenously or via auto-injection. Treatment options also include light therapy, topical medications, and oral medications.', 'ingredient_treatments': []}
{'original_treatments': 'Alpha-hydroxy acid cream, tretinoin cream', 'ingredient_treatments': ['Alpha-hydroxy acid', 'tretinoin']}
{'original_treatments': 'Terbinafine, fluconazole, or itraconazole', 'ingredient_treatments': ['terbinafine', 'fluconazole', 'itraconazole']}
{'original_treatments': 'Aminolevulinic acid, methylaminolevulinate', 'ingredient_treatments': ['Aminolevulinic acid', 'methylaminolevulinate']}
{'original_treatments': 'There is no single treatment that reliably manages the pain, but it is common to try multiple options. These options include topical agents like lidocaine or capsaicin patches, certain antidepressants such as duloxetine or venlafaxine, and specific anticonvulsants such as gabapentin and pregabalin.', 'ingredient_treatments': ['lidocaine', 'capsaicin', 'duloxetine', 'venlafaxine', 'gabapentin', 'pregabalin']}
{'original_treatments': 'Malathion, permethrin cream, and pyrethrins', 'ingredient_treatments': ['Malathion', 'permethrin', 'pyrethrins']}
{'original_treatments': 'Aspirin and intravenous gamma globulin (IVIG)', 'ingredient_treatments': ['aspirin', 'gamma globulin']}
{'original_treatments': 'Chloroquine, mefloquine, atovaquone-proguanil', 'ingredient_treatments': ['Chloroquine', 'mefloquine', 'atovaquone', 'proguanil']}
{'original_treatments': 'Ointments, creams, lotions, gels and powders.', 'ingredient_treatments': []}
{'original_treatments': 'Selenium sulfide, zinc pyrithione, tar, sulfur', 'ingredient_treatments': ['Selenium sulfide', 'zinc pyrithione', 'tar', 'sulfur']}
{'original_treatments': 'There is no cure for monilethrix. However, spontaneous regression can occur during puberty or pregnancy, and some patients have experienced success with topical minoxidil 2%.  Steroid preparations, retinoids, glycolic acids, oral contraceptives, and vitamins can also be used, but with limited success.', 'ingredient_treatments': ['minoxidil', 'steroids', 'retinoids', 'glycolic acids', 'vitamins']}
{'original_treatments': 'Chemical peels, surgery, lasers, or cryotherapy.', 'ingredient_treatments': []}
{'original_treatments': 'Oral antibiotics like tetracycline, topical creams like Metrogel, Cleocin-T, or Azelex, and oral Accutane are effective treatments. Mild cases may be managed with warm compresses for the eyes. Makeup can be used to cover redness, and hormone replacement therapy may be helpful for menopausal hot flashes.', 'ingredient_treatments': ['tetracycline', 'Metrogel', 'Cleocin-T', 'Azelex', 'Accutane']}
{'original_treatments': 'Treatment options include topical medications like benzoyl peroxide and salicylic acid, oral antibiotics, and in severe cases, oral retinoids like isotretinoin (Accutane).  Procedures such as chemical peels, laser resurfacing, and microdermabrasion can also be used to improve the appearance of acne scars.', 'ingredient_treatments': ['benzoyl peroxide', 'salicylic acid', 'isotretinoin']}
{'original_treatments': 'Minocycline, ibuprofen, penicillin, Vitamin C 500mg', 'ingredient_treatments': ['Minocycline', 'ibuprofen', 'penicillin', 'Vitamin C']}
{'original_treatments': 'The primary treatment for glomus tumors is surgical excision. Laser and sclerotherapy are sometimes used as alternative treatments. If multiple tumors are present, laser therapy, argon, carbon dioxide or Nd:YAG laser therapy, or sclerotherapy with hypertonic saline or sodium tetradecyl sulfate may be used.', 'ingredient_treatments': ['hypertonic saline', 'sodium tetradecyl sulfate']}
{'original_treatments': 'There is no cure for XP, but treatment focuses on protecting the skin from sunlight and early detection and treatment of skin cancer. This includes avoiding sun exposure, wearing protective clothing, and using sunscreen. Regular dermatological checkups are crucial for early detection of any cancerous growths.', 'ingredient_treatments': ['sunscreen']}
{'original_treatments': 'Retinol, Tretinoin, Adapalene, Tazarotene, Alitretinoin', 'ingredient_treatments': ['Retinol', 'Tretinoin', 'Adapalene', 'Tazarotene', 'Alitretinoin']}
{'original_treatments': 'Topical steroids such as hydrocortisone or triamcinolone', 'ingredient_treatments': ['hydrocortisone', 'triamcinolone']}
{'original_treatments': 'Treatment for drug eruptions involves identifying and withdrawing the offending agent.  In mild cases, treatment is supportive and may include anti-histamines, topical steroids, and moisturizing lotions. Severe cases may require hospitalization and treatment with intravenous immunoglobulin or systemic steroids.', 'ingredient_treatments': ['steroids']}
{'original_treatments': 'Hydroquinone, tretinoin, cortisone cream, laser treatments', 'ingredient_treatments': ['Hydroquinone', 'tretinoin', 'cortisone']}
{'original_treatments': 'Oral prednisone, dapsone, potassium iodine, and colchicine', 'ingredient_treatments': ['prednisone', 'dapsone', 'potassium iodine', 'colchicine']}
{'original_treatments': 'Antihistamines and pulsed dye laser treatments can be used.', 'ingredient_treatments': []}
{'original_treatments': 'Methotrexate, cyclosporin, phototherapy (ultraviolet lights)', 'ingredient_treatments': ['Methotrexate', 'cyclosporin']}
{'original_treatments': 'Alpha-hydroxy acids, trichloroacetic acid, stronger chemicals', 'ingredient_treatments': ['Alpha-hydroxy acids', 'trichloroacetic acid']}
{'original_treatments': 'Silver sulfadiazine cream, white vinegar, or oral antibiotics.', 'ingredient_treatments': ['silver sulfadiazine']}
{'original_treatments': 'Systemic retinoids have shown to control skin lesions.  Treatment with rapamycin is under clinical trial and has shown promising outcomes in the regression of skin manifestations.  Chemical peels, dermabrasion, and laser resurfacing may be helpful.  Surgery should be done with care because of scarring and recurrence.', 'ingredient_treatments': ['retinoids', 'rapamycin']}
{'original_treatments': 'Cryotherapy, laser treatment, or conservative surgical excision', 'ingredient_treatments': []}
{'original_treatments': 'Penicillin, cephalosporin, erythromycin, intravenous antibiotics', 'ingredient_treatments': ['Penicillin', 'cephalosporin', 'erythromycin']}
{'original_treatments': 'Podophyllin, Imiquimod, cryotherapy, various acids, 5-FU 5% cream', 'ingredient_treatments': ['Podophyllin', 'Imiquimod', '5-FU', 'various acids']}
{'original_treatments': 'Removal with light electrodesiccation, cryosurgery, or curettage.', 'ingredient_treatments': []}
{'original_treatments': 'Salicylic acid, tretinoin cream, Condylox solution, griseofulvin', 'ingredient_treatments': ['salicylic acid', 'tretinoin', 'griseofulvin']}

100%|██████████| 1/1 [00:00<00:00, 6141.00it/s]

In [115]:
%%bigquery
create or replace table skincare_products_stg.dermatologic_disease as
  select name, physical_description, causes,
  JSON_EXTRACT_ARRAY(treatments) as treatments,
  _data_source,
  _load_time
  from skincare_products_stg.dermatologic_disease;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

#### Standardize treatment ingredients using LLM

##### View list of treatment ingredients

In [121]:
%%bigquery
WITH flattened_treatments AS (
  -- Flatten the array into individual rows
  SELECT
    LOWER(TRIM(treatment)) AS treatment -- Convert to lowercase and trim spaces to handle case/whitespace variations
  FROM
    skincare_products_stg.dermatologic_disease,
    UNNEST(treatments) AS treatment -- Unnest the arrays into individual strings
  WHERE
    treatments IS NOT NULL
)
-- Select distinct treatments and sort them alphabetically
SELECT DISTINCT treatment as ingredient
FROM flattened_treatments
ORDER BY ingredient;

Query is running:   0%|          |

Downloading:   0%|          |

            ingredient
0     "5-fluorouracil"
1               "5-fu"
2        "abrocitinib"
3           "accolate"
4           "accutane"
..                 ...
324   "wheat germ oil"
325       "zinc oxide"
326  "zinc pyrithione"
327     "zinc sulfate"
328          "zovirax"

[329 rows x 1 columns]

##### Create standardized ingredient names

In [124]:
import json
import pandas_gbq
import numpy as np
import vertexai
from vertexai.generative_models import GenerativeModel, Part
from google.cloud import bigquery
import pandas as pd
import ast


project_id = "segfault-434120"
region = "us-central1"
dataset_id = "skincare_products_stg"
model_name = "gemini-1.5-flash-001"
prompt = """Go through this list of ingredients and look for ingredients that have similar meanings, but were given different names.
For example, '5-FU' and '5-fluorouracil' have similar meanings and 'alpha-hydroxy acid' and 'alpha hydroxyacids' have similar meanings.
Suggest a standard ingredient name, mapping the current one to the new one.
Return the list of original ingredient names along with their new ingredient names.
Format the results as a json object with the schema: current_ingredient:string, new_ingredient:string.
Do not include any unchanged ingredient names with your answer.
Do not include an explanation with your answer.
"""

ingredients_sql = """
WITH flattened_treatments AS (
  -- Flatten the array into individual rows
  SELECT
    LOWER(TRIM(treatment)) AS treatment -- Convert to lowercase and trim spaces to handle case/whitespace variations
  FROM
    skincare_products_stg.dermatologic_disease,
    UNNEST(treatments) AS treatment -- Unnest the arrays into individual strings
  WHERE
    treatments IS NOT NULL
)
-- Select distinct treatments and sort them alphabetically
SELECT DISTINCT treatment as ingredient
FROM flattened_treatments
ORDER BY ingredient;
"""

dermatologic_disease_sql = "select * from skincare_products_stg.dermatologic_disease"

bq_client = bigquery.Client()
ingredient_rows = bq_client.query_and_wait(ingredients_sql)

ingredient_list = []
for row in ingredient_rows:
    ingredient_list.append(row["ingredient"])
category_str = '\n'.join(ingredient_list)
#print("category_str:", category_str)

vertexai.init(project=project_id, location=region)
model = GenerativeModel(model_name)
resp = model.generate_content(contents=[category_str, prompt], safety_settings={
                HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
            })
resp_text = resp.text.replace("```json", "").replace("```", "").replace("\n", "")
print(resp_text)
ingredients = json.loads(resp_text)
print(type(ingredients))

replacements = {} # will store the new ingredients

# ingredients can be either a dictionary or list type (depending on what LLM decides to do!)
if type(ingredients) == dict:
    for old, new in ingredients.items():
        if old == new:
            continue
        else:
            replacements[old] = new

if type(ingredients) == list:
    for cat_entry in ingredients:
        if cat_entry['current_ingredient'] == cat_entry['new_ingredient']:
            continue
        else:
            replacements[cat_entry['current_ingredient']] = cat_entry['new_ingredient']


# lowercase all ingredient names
replacements = {key.lower(): value.lower() for key, value in replacements.items()}
print("replacements:", replacements)

{"5-fu": "5-fluorouracil","alpha hydroxyacids": "alpha-hydroxy acid","alpha hydroxyl acids": "alpha-hydroxy acid","anti-bacterials": "antibiotics","anti-dandruff shampoo": "selenium sulfide","anti-fungal creams": "clotrimazole","anti-fungal powder": "clotrimazole","anti-inflammatory pills": "ibuprofen","botulinum toxin": "botulinum toxin a","calcineurin inhibitors": "tacrolimus","calcipotriol": "calcipotriene","calcium channel blockers": "nifedipine","capsaicin": "capasaicin","cephalosporin": "cephalosporins","chlorine bleach": "bleach","cleocin-t": "clindamycin","clindamycin hcl": "clindamycin","coal tar": "tar","corticosteroid medications": "corticosteroids","corticosteroid": "corticosteroids","cortisone": "corticosteroids","cromolyn": "cromolyn sodium","cyclosporin": "cyclosporine","cytoxan": "cyclophosphamide","diclofenac sodium": "diclofenac","diosmiplex": "diosmin","doxycycline": "tetracyclines","elavil": "amitriptyline","famvir": "famciclovir","fluids": "electrolytes","fluorouracil": "5-fluorouracil","glycolic acids": "glycolic acid","gotu kola extract": "centella asiatica","high-estrogen birth control pills": "estrogen","hydrocortisone": "corticosteroids","immune modulators": "immunosuppressants","immunosuppressants": "immunosuppressive agents","immunosuppressive agents": "immunosuppressive drugs","imuran": "azathioprine","interferon": "interferon-alpha","interferon-alfa": "interferon-alpha","intravenous immunoglobulin": "gamma globulin","isotretinoin": "retinoids","keratolytics": "salicylic acid","lactic acid": "alpha-hydroxy acid","loprox": "loperamide","lotrimin af": "clotrimazole","macrolide class antibiotics": "azithromycin","malic acid": "alpha-hydroxy acid","mek inhibitors": "trametinib","metrogel": "metronidazole","micatin": "miconazole","minocycline": "tetracyclines","neoral": "cyclosporine","neurontin": "gabapentin","niacinamide": "niacin","nicotinamide": "niacin","nizoral": "ketoconazole","nsaids": "ibuprofen","oral antibiotics": "antibiotics","oral steroids": "corticosteroids","organochlorine insecticides": "lindane","pain relievers": "ibuprofen","petrolatum": "petroleum jelly","pd-1 inhibitors": "nivolumab","penicillin": "antibiotics","podophyllin resin": "podophyllin","podophyllum": "podophyllin","potassium iodine": "potassium iodide","prednisolone": "corticosteroids","prednisone": "corticosteroids","prostaglandin analogues": "latanoprost","proton pump inhibitors": "omeprazole","retinoid creams": "retinoids","retinoid": "retinoids","retinol": "retinoids","rifampin": "rifampicin","soriatane": "acitretin","spf 25": "sunscreen","spinosad": "insecticide","sporonox": "itraconazole","steroid gels": "corticosteroids","steroid": "corticosteroids","steroids": "corticosteroids","systemic corticosteroids": "corticosteroids","tar": "coal tar","tartaric acid": "alpha-hydroxy acid","tazarotene": "retinoids","tca": "trichloroacetic acid","tegretol": "carbamazepine","tetracycline": "tetracyclines","thalidomide": "immunosuppressant","topical antibiotics": "antibiotics","topical corticosteroids": "corticosteroids","topical medications": "medications","topical retinoids": "retinoids","topical steroids": "corticosteroids","tretinoin": "retinoids","triamcinalone": "triamcinolone","trichloroacetic acid (tca)": "trichloroacetic acid","trichloroacetic acid": "trichloroacetic acid","tricyclic antidepressants": "amitriptyline","triple paste": "zinc oxide","urea": "keratolytic","valtrex": "valacyclovir","various acids": "alpha-hydroxy acid","vinegar (acetic acid)": "acetic acid","vitamin a": "retinol","vitamin d analogs": "vitamin d","vitamin d": "calcitriol","vitamin e": "tocopherol","vitamins": "nutrients","zovirax": "acyclovir"}
<class 'dict'>
replacements: {'5-fu': '5-fluorouracil', 'alpha hydroxyacids': 'alpha-hydroxy acid', 'alpha hydroxyl acids': 'alpha-hydroxy acid', 'anti-bacterials': 'antibiotics', 'anti-dandruff shampoo': 'selenium sulfide', 'anti-fungal creams': 'clotrimazole', 'anti-fungal powder': 'clotrimazole', 'anti-inflammatory pills': 'ibuprofen', 'botulinum toxin': 'botulinum toxin a', 'calcineurin inhibitors': 'tacrolimus', 'calcipotriol': 'calcipotriene', 'calcium channel blockers': 'nifedipine', 'capsaicin': 'capasaicin', 'cephalosporin': 'cephalosporins', 'chlorine bleach': 'bleach', 'cleocin-t': 'clindamycin', 'clindamycin hcl': 'clindamycin', 'coal tar': 'tar', 'corticosteroid medications': 'corticosteroids', 'corticosteroid': 'corticosteroids', 'cortisone': 'corticosteroids', 'cromolyn': 'cromolyn sodium', 'cyclosporin': 'cyclosporine', 'cytoxan': 'cyclophosphamide', 'diclofenac sodium': 'diclofenac', 'diosmiplex': 'diosmin', 'doxycycline': 'tetracyclines', 'elavil': 'amitriptyline', 'famvir': 'famciclovir', 'fluids': 'electrolytes', 'fluorouracil': '5-fluorouracil', 'glycolic acids': 'glycolic acid', 'gotu kola extract': 'centella asiatica', 'high-estrogen birth control pills': 'estrogen', 'hydrocortisone': 'corticosteroids', 'immune modulators': 'immunosuppressants', 'immunosuppressants': 'immunosuppressive agents', 'immunosuppressive agents': 'immunosuppressive drugs', 'imuran': 'azathioprine', 'interferon': 'interferon-alpha', 'interferon-alfa': 'interferon-alpha', 'intravenous immunoglobulin': 'gamma globulin', 'isotretinoin': 'retinoids', 'keratolytics': 'salicylic acid', 'lactic acid': 'alpha-hydroxy acid', 'loprox': 'loperamide', 'lotrimin af': 'clotrimazole', 'macrolide class antibiotics': 'azithromycin', 'malic acid': 'alpha-hydroxy acid', 'mek inhibitors': 'trametinib', 'metrogel': 'metronidazole', 'micatin': 'miconazole', 'minocycline': 'tetracyclines', 'neoral': 'cyclosporine', 'neurontin': 'gabapentin', 'niacinamide': 'niacin', 'nicotinamide': 'niacin', 'nizoral': 'ketoconazole', 'nsaids': 'ibuprofen', 'oral antibiotics': 'antibiotics', 'oral steroids': 'corticosteroids', 'organochlorine insecticides': 'lindane', 'pain relievers': 'ibuprofen', 'petrolatum': 'petroleum jelly', 'pd-1 inhibitors': 'nivolumab', 'penicillin': 'antibiotics', 'podophyllin resin': 'podophyllin', 'podophyllum': 'podophyllin', 'potassium iodine': 'potassium iodide', 'prednisolone': 'corticosteroids', 'prednisone': 'corticosteroids', 'prostaglandin analogues': 'latanoprost', 'proton pump inhibitors': 'omeprazole', 'retinoid creams': 'retinoids', 'retinoid': 'retinoids', 'retinol': 'retinoids', 'rifampin': 'rifampicin', 'soriatane': 'acitretin', 'spf 25': 'sunscreen', 'spinosad': 'insecticide', 'sporonox': 'itraconazole', 'steroid gels': 'corticosteroids', 'steroid': 'corticosteroids', 'steroids': 'corticosteroids', 'systemic corticosteroids': 'corticosteroids', 'tar': 'coal tar', 'tartaric acid': 'alpha-hydroxy acid', 'tazarotene': 'retinoids', 'tca': 'trichloroacetic acid', 'tegretol': 'carbamazepine', 'tetracycline': 'tetracyclines', 'thalidomide': 'immunosuppressant', 'topical antibiotics': 'antibiotics', 'topical corticosteroids': 'corticosteroids', 'topical medications': 'medications', 'topical retinoids': 'retinoids', 'topical steroids': 'corticosteroids', 'tretinoin': 'retinoids', 'triamcinalone': 'triamcinolone', 'trichloroacetic acid (tca)': 'trichloroacetic acid', 'tricyclic antidepressants': 'amitriptyline', 'triple paste': 'zinc oxide', 'urea': 'keratolytic', 'valtrex': 'valacyclovir', 'various acids': 'alpha-hydroxy acid', 'vinegar (acetic acid)': 'acetic acid', 'vitamin a': 'retinol', 'vitamin d analogs': 'vitamin d', 'vitamin d': 'calcitriol', 'vitamin e': 'tocopherol', 'vitamins': 'nutrients', 'zovirax': 'acyclovir'}

##### Replace treatment ingredient names with their standardized name

In [125]:
# Function to replace ingredients in each treatment list
def replace_ingredients(treatments, replacements_dict):
    print("original treatments: ", treatments)

    # Check if treatments is NULL or not a list (e.g., None)
    if treatments is None or not isinstance(treatments, list):
        return treatments

    # Check if treatments array is empty
    if len(treatments) == 0:
        return treatments

    standardized_treatments = []

    # Iterate through each ingredient in the treatments array
    treatments = [x.lower() for x in treatments]
    for ingredient in treatments:
        ingredient = ingredient.replace("\"", "")

        # Replace with standardized name if it exists in the replacements dictionary
        standardized_ingredient = replacements_dict.get(ingredient, ingredient)
        standardized_treatments.append(standardized_ingredient)

    print("standardized_treatments: ", standardized_treatments)
    return standardized_treatments

# Function to safely apply literal_eval only when needed
def ensure_list(val):
    # If the value is a NumPy array, convert it to a list
    if isinstance(val, np.ndarray):
        # print("original nparray val: ", val)
        val_as_list = val.tolist()
        # print("list val: ", val_as_list)

        # If tolist() returns a string or other non-list type, wrap it in a list
        if isinstance(val_as_list, str):
            # print("wrapped val: ", [val_as_list])
            return [val_as_list]

        return val_as_list

# Fetch the data from BigQuery into a DataFrame
disease_rows = pandas_gbq.read_gbq(dermatologic_disease_sql, project_id=project_id)

# Convert lists to JSON strings for BigQuery compatibility
disease_rows["treatments"] = disease_rows["treatments"].apply(ensure_list)
disease_rows["treatments"] = disease_rows["treatments"].apply(lambda x: replace_ingredients(x, replacements))
disease_rows["treatments"] = disease_rows["treatments"].apply(lambda x: json.dumps(x) if isinstance(x, list) else x)

# # Apply the replacement to each row's treatments list
# print("new df:", disease_rows)

# # Upload the updated DataFrame back to BigQuery
table_id = f"{project_id}.skincare_products_stg.dermatologic_disease"
pandas_gbq.to_gbq(disease_rows, table_id, project_id=project_id, if_exists='replace')

Downloading: 100%|██████████|
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  []
original treatments:  ['"TCA"', '"podophyllin"', '"phenol"', '"silver nitrate"']
standardized_treatments:  ['trichloroacetic acid', 'podophyllin', 'phenol', 'silver nitrate']
original treatments:  ['"Urea"', '"Alpha-hydroxy acids"', '"antibiotics"', '"retinoid creams"']
standardized_treatments:  ['keratolytic', 'alpha-hydroxy acids', 'antibiotics', 'retinoids']
original treatments:  ['"urea"', '"lactic acid"', '"oatmeal"', '"menthol"', '"camphor"']
standardized_treatments:  ['keratolytic', 'alpha-hydroxy acid', 'oatmeal', 'menthol', 'camphor']
original treatments:  ['"urea"', '"lactic acid"', '"steroids"', '"retinoids"']
standardized_treatments:  ['keratolytic', 'alpha-hydroxy acid', 'corticosteroids', 'retinoids']
original treatments:  ['"CTLA-4"', '"PD-1 inhibitors"', '"BRAF"', '"MEK inhibitors"']
standardized_treatments:  ['ctla-4', 'nivolumab', 'braf', 'trametinib']
original treatments:  ['"Famvir"', '"Zovirax"', '"Valtrex"', '"Neurontin"', '"Tegretol"', '"Elavil"', '"cortisone"']
standardized_treatments:  ['famciclovir', 'acyclovir', 'valacyclovir', 'gabapentin', 'carbamazepine', 'amitriptyline', 'corticosteroids']
original treatments:  ['"NSAIDs"']
standardized_treatments:  ['ibuprofen']
original treatments:  ['"SPF 25"']
standardized_treatments:  ['sunscreen']
original treatments:  ['"Thymol"']
standardized_treatments:  ['thymol']
original treatments:  ['"fluids"', '"electrolytes"']
standardized_treatments:  ['electrolytes', 'electrolytes']
original treatments:  ['"niacin"', '"niacinamide"']
standardized_treatments:  ['niacin', 'niacin']
original treatments:  ['"saline"']
standardized_treatments:  ['saline']
original treatments:  ['"silver"']
standardized_treatments:  ['silver']
original treatments:  ['"thymol"', '"mupirocin"']
standardized_treatments:  ['thymol', 'mupirocin']
original treatments:  ['"Danazol"', '"Diosmiplex"', '"Oxandrolone"', '"Pentoxifylline"']
standardized_treatments:  ['danazol', 'diosmin', 'oxandrolone', 'pentoxifylline']
original treatments:  ['"Dapsone"']
standardized_treatments:  ['dapsone']
original treatments:  ['"Dapsone"', '"sulfapyridine"', '"tetracycline"']
standardized_treatments:  ['dapsone', 'sulfapyridine', 'tetracyclines']
original treatments:  ['"Dapsone"', '"sulfapyridine"', '"mycophenolate mofetil"', '"colchicine"', '"dicloxacillin"', '"corticosteroids"']
standardized_treatments:  ['dapsone', 'sulfapyridine', 'mycophenolate mofetil', 'colchicine', 'dicloxacillin', 'corticosteroids']
original treatments:  ['"Nizoral"', '"Loprox"', '"Sporonox"']
standardized_treatments:  ['ketoconazole', 'loperamide', 'itraconazole']
original treatments:  ['"Retinol"', '"Tretinoin"', '"Adapalene"', '"Tazarotene"', '"Alitretinoin"']
standardized_treatments:  ['retinoids', 'retinoids', 'adapalene', 'retinoids', 'alitretinoin']
original treatments:  ['"Zovirax"', '"Valtrex"', '"Cytoxan"', '"cyclosporin"', '"prednisone"']
standardized_treatments:  ['acyclovir', 'valacyclovir', 'cyclophosphamide', 'cyclosporine', 'corticosteroids']
original treatments:  ['"aspirin"', '"gabapentin"', '"misoprostol"']
standardized_treatments:  ['aspirin', 'gabapentin', 'misoprostol']
original treatments:  ['"aspirin"', '"gamma globulin"']
standardized_treatments:  ['aspirin', 'gamma globulin']
original treatments:  ['"dapsone"', '"rifampin"', '"clofazimine"', '"oflozacin"', '"minocycline"']
standardized_treatments:  ['dapsone', 'rifampicin', 'clofazimine', 'oflozacin', 'tetracyclines']
original treatments:  ['"lindane"', '"sulfur"', '"ivermectin"']
standardized_treatments:  ['lindane', 'sulfur', 'ivermectin']
original treatments:  ['"menthol"', '"pramoxine"', '"phenol"', '"cortisone"', '"prednisone"', '"cyclosporine"', '"hydroxychloroquine"']
standardized_treatments:  ['menthol', 'pramoxine', 'phenol', 'corticosteroids', 'corticosteroids', 'cyclosporine', 'hydroxychloroquine']
original treatments:  ['"oatmeal"', '"prednisone"', '"erythromycin"']
standardized_treatments:  ['oatmeal', 'corticosteroids', 'erythromycin']
original treatments:  ['"steroid"']
standardized_treatments:  ['corticosteroids']
original treatments:  ['"Accutane"', '"Soriatane"', '"methotrexate"']
standardized_treatments:  ['accutane', 'acitretin', 'methotrexate']
original treatments:  ['"Accutane"', '"antibiotics"']
standardized_treatments:  ['accutane', 'antibiotics']
original treatments:  ['"Benadryl"', '"dapsone"']
standardized_treatments:  ['benadryl', 'dapsone']
original treatments:  ['"Imatinib"']
standardized_treatments:  ['imatinib']
original treatments:  ['"calamine"', '"corticosteroids"']
standardized_treatments:  ['calamine', 'corticosteroids']
original treatments:  ['"cromolyn"']
standardized_treatments:  ['cromolyn sodium']
original treatments:  ['"estrogen"']
standardized_treatments:  ['estrogen']
original treatments:  ['"fluoride"']
standardized_treatments:  ['fluoride']
original treatments:  ['"psoralen"']
standardized_treatments:  ['psoralen']
original treatments:  ['"psoralen"']
standardized_treatments:  ['psoralen']
original treatments:  ['"psoralen"', '"capasaicin"']
standardized_treatments:  ['psoralen', 'capasaicin']
original treatments:  ['"steroids"']
standardized_treatments:  ['corticosteroids']
original treatments:  ['"steroids"']
standardized_treatments:  ['corticosteroids']
original treatments:  ['"steroids"']
standardized_treatments:  ['corticosteroids']
original treatments:  ['"steroids"']
standardized_treatments:  ['corticosteroids']
original treatments:  ['"steroids"', '"methotrexate"']
standardized_treatments:  ['corticosteroids', 'methotrexate']
original treatments:  ['"steroids"', '"tetracyclines"', '"isotretinoin"']
standardized_treatments:  ['corticosteroids', 'tetracyclines', 'retinoids']
original treatments:  ['"steroids"', '"immune modulators"']
standardized_treatments:  ['corticosteroids', 'immunosuppressants']
original treatments:  ['"Capsaicin"', '"pramoxine"', '"doxepin"', '"amitriptyline"', '"ketamine"', '"gabapentin"', '"lamotrigine"', '"carbamazepine"', '"valproate"']
standardized_treatments:  ['capasaicin', 'pramoxine', 'doxepin', 'amitriptyline', 'ketamine', 'gabapentin', 'lamotrigine', 'carbamazepine', 'valproate']
original treatments:  ['"Imiquimod"', '"Trichloracetic acid (TCA)"', '"interferon"']
standardized_treatments:  ['imiquimod', 'trichloracetic acid (tca)', 'interferon-alpha']
original treatments:  ['"Malathion"', '"Permethrin"', '"Ivermectin"']
standardized_treatments:  ['malathion', 'permethrin', 'ivermectin']
original treatments:  ['"Malathion"', '"permethrin"', '"pyrethrins"']
standardized_treatments:  ['malathion', 'permethrin', 'pyrethrins']
original treatments:  ['"Minoxidil"', '"Finasteride"', '"prostaglandin analogues"']
standardized_treatments:  ['minoxidil', 'finasteride', 'latanoprost']
original treatments:  ['"Mupirocin"']
standardized_treatments:  ['mupirocin']
original treatments:  ['"Tretinoin"', '"urea"', '"alpha hydroxyacids"', '"lactic acid"', '"salicylic acid"']
standardized_treatments:  ['retinoids', 'keratolytic', 'alpha-hydroxy acid', 'alpha-hydroxy acid', 'salicylic acid']
original treatments:  ['"acitretin"']
standardized_treatments:  ['acitretin']
original treatments:  ['"acitretin"', '"steroids"', '"tacrolimus"']
standardized_treatments:  ['acitretin', 'corticosteroids', 'tacrolimus']
original treatments:  ['"acitretin"', '"isotretinoin"']
standardized_treatments:  ['acitretin', 'retinoids']
original treatments:  ['"capsaicin"', '"psoralen"']
standardized_treatments:  ['capasaicin', 'psoralen']
original treatments:  ['"capsaicin"', '"steroids"', '"pramoxine"', '"lidocaine"', '"prilocaine"', '"gabapentin"', '"amitriptyline"', '"methylprednisolone"']
standardized_treatments:  ['capasaicin', 'corticosteroids', 'pramoxine', 'lidocaine', 'prilocaine', 'gabapentin', 'amitriptyline', 'methylprednisolone']
original treatments:  ['"cortisone"']
standardized_treatments:  ['corticosteroids']
original treatments:  ['"cortisone"']
standardized_treatments:  ['corticosteroids']
original treatments:  ['"cortisone"']
standardized_treatments:  ['corticosteroids']
original treatments:  ['"cortisone"', '"aspirin"', '"prednisone"']
standardized_treatments:  ['corticosteroids', 'aspirin', 'corticosteroids']
original treatments:  ['"cortisone"', '"Accutane"', '"tetracycline"', '"cortisone"']
standardized_treatments:  ['corticosteroids', 'accutane', 'tetracyclines', 'corticosteroids']
original treatments:  ['"cortisone"', '"coal tar"']
standardized_treatments:  ['corticosteroids', 'tar']
original treatments:  ['"cortisone"', '"pimecrolimus"', '"tacrolimus"', '"imiquimod"', '"hydroxychloroquine"', '"chloroquine"', '"quinacrine"', '"Accutane"', '"Soriatane"']
standardized_treatments:  ['corticosteroids', 'pimecrolimus', 'tacrolimus', 'imiquimod', 'hydroxychloroquine', 'chloroquine', 'quinacrine', 'accutane', 'acitretin']
original treatments:  ['"cortisone"', '"corticosteroid"']
standardized_treatments:  ['corticosteroids', 'corticosteroids']
original treatments:  ['"ibuprofen"', '"steroids"']
standardized_treatments:  ['ibuprofen', 'corticosteroids']
original treatments:  ['"imiquimod"']
standardized_treatments:  ['imiquimod']
original treatments:  ['"imiquimod"']
standardized_treatments:  ['imiquimod']
original treatments:  ['"imiquimod"', '"interferon-alfa"']
standardized_treatments:  ['imiquimod', 'interferon-alpha']
original treatments:  ['"lidocaine"', '"capsaicin"', '"duloxetine"', '"venlafaxine"', '"gabapentin"', '"pregabalin"']
standardized_treatments:  ['lidocaine', 'capasaicin', 'duloxetine', 'venlafaxine', 'gabapentin', 'pregabalin']
original treatments:  ['"lidocaine"', '"methylprednisolone"', '"botulinum toxin"', '"capsaicin"', '"lidocaine"', '"tricyclic antidepressants"', '"gabapentin"']
standardized_treatments:  ['lidocaine', 'methylprednisolone', 'botulinum toxin a', 'capasaicin', 'lidocaine', 'amitriptyline', 'gabapentin']
original treatments:  ['"minoxidil"', '"steroids"', '"retinoids"', '"glycolic acids"', '"vitamins"']
standardized_treatments:  ['minoxidil', 'corticosteroids', 'retinoids', 'glycolic acid', 'nutrients']
original treatments:  ['"minoxidil"', '"anthralin"']
standardized_treatments:  ['minoxidil', 'anthralin']
original treatments:  ['"minoxidil"', '"Spironolactone"']
standardized_treatments:  ['minoxidil', 'spironolactone']
original treatments:  ['"mupirocin"', '"retapamulin"']
standardized_treatments:  ['mupirocin', 'retapamulin']
original treatments:  ['"retinoids"', '"steroids"']
standardized_treatments:  ['retinoids', 'corticosteroids']
original treatments:  ['"retinoids"', '"rapamycin"']
standardized_treatments:  ['retinoids', 'rapamycin']
original treatments:  ['"retinoids"', '"hydroquinone"', '"alpha hydroxyl acids"']
standardized_treatments:  ['retinoids', 'hydroquinone', 'alpha-hydroxy acid']
original treatments:  ['"retinoids"', '"isotretinoin"']
standardized_treatments:  ['retinoids', 'retinoids']
original treatments:  ['"sunscreen"']
standardized_treatments:  ['sunscreen']
original treatments:  ['"sunscreen"', '"corticosteroids"', '"antibiotics"', '"dapsone"', '"tacrolimus"']
standardized_treatments:  ['sunscreen', 'corticosteroids', 'antibiotics', 'dapsone', 'tacrolimus']
original treatments:  ['"vitamin A"']
standardized_treatments:  ['retinol']
original treatments:  ['"Bexarotene"', '"Interferon-alpha"', '"methotrexate"']
standardized_treatments:  ['bexarotene', 'interferon-alpha', 'methotrexate']
original treatments:  ['"Ivermectin"', '"Albendazole"', '"thiabendazole"', '"metronidazole"']
standardized_treatments:  ['ivermectin', 'albendazole', 'thiabendazole', 'metronidazole']
original treatments:  ['"Penicillin"', '"cephalosporin"', '"erythromycin"']
standardized_treatments:  ['antibiotics', 'cephalosporins', 'erythromycin']
original treatments:  ['"Permethrin"', '"pyrethrins"', '"organochlorine insecticides"', '"malathion"', '"benzyl alcohol"', '"spinosad"', '"ivermectin"']
standardized_treatments:  ['permethrin', 'pyrethrins', 'lindane', 'malathion', 'benzyl alcohol', 'insecticide', 'ivermectin']
original treatments:  ['"Prednisone"', '"Imuran"', '"Cytoxan"', '"gold"', '"cyclosporin"', '"steroids"', '"Hydroxychloroquine"', '"dapsone"']
standardized_treatments:  ['corticosteroids', 'azathioprine', 'cyclophosphamide', 'gold', 'cyclosporine', 'corticosteroids', 'hydroxychloroquine', 'dapsone']
original treatments:  ['"bacitracin"', '"polymyxin B"', '"chlorine bleach"', '"vinegar (acetic acid)"', '"ciprofloxacin"']
standardized_treatments:  ['bacitracin', 'polymyxin b', 'bleach', 'acetic acid', 'ciprofloxacin']
original treatments:  ['"colchicine"', '"dapsone"', '"systemic corticosteroids"', '"immunosuppressive agents"']
standardized_treatments:  ['colchicine', 'dapsone', 'corticosteroids', 'immunosuppressive drugs']
original treatments:  ['"colchicine"', '"tetracycline"', '"dapsone"']
standardized_treatments:  ['colchicine', 'tetracyclines', 'dapsone']
original treatments:  ['"dichlorvos"']
standardized_treatments:  ['dichlorvos']
original treatments:  ['"ivermectin"', '"malathion"']
standardized_treatments:  ['ivermectin', 'malathion']
original treatments:  ['"methyldopa"', '"prazosin"', '"nifedipine"', '"verapamil"', '"pentoxifylline"', '"nitroglycerine"', '"paraffin"']
standardized_treatments:  ['methyldopa', 'prazosin', 'nifedipine', 'verapamil', 'pentoxifylline', 'nitroglycerine', 'paraffin']
original treatments:  ['"paclitaxel"']
standardized_treatments:  ['paclitaxel']
original treatments:  ['"penicillin"', '"erythromycin"', '"cephalosporins"', '"acetaminophen"']
standardized_treatments:  ['antibiotics', 'erythromycin', 'cephalosporins', 'acetaminophen']
original treatments:  ['"penicillin"', '"cephalosporin"', '"erythromycin"', '"ceftriaxone"']
standardized_treatments:  ['antibiotics', 'cephalosporins', 'erythromycin', 'ceftriaxone']
original treatments:  ['"petrolatum"', '"corticosteroids"', '"retinoids"']
standardized_treatments:  ['petroleum jelly', 'corticosteroids', 'retinoids']
original treatments:  ['"prednisone"', '"dapsone"', '"potassium iodine"', '"colchicine"']
standardized_treatments:  ['corticosteroids', 'dapsone', 'potassium iodide', 'colchicine']
original treatments:  ['"pyridoxine"', '"rituximab"', '"dapsone"', '"cyclophosphamide"', '"methotrexate"', '"nicotinamide"']
standardized_treatments:  ['pyridoxine', 'rituximab', 'dapsone', 'cyclophosphamide', 'methotrexate', 'niacin']
original treatments:  ['"tacrolimus"', '"retinoids"', '"calcipotriene"']
standardized_treatments:  ['tacrolimus', 'retinoids', 'calcipotriene']
original treatments:  ['"tacrolimus"', '"pimecrolimus"']
standardized_treatments:  ['tacrolimus', 'pimecrolimus']
original treatments:  ['"zinc oxide"', '"Triple paste"', '"Lotrimin AF"', '"Micatin"']
standardized_treatments:  ['zinc oxide', 'zinc oxide', 'clotrimazole', 'miconazole']
original treatments:  ['"Chloroquine"', '"mefloquine"', '"atovaquone"', '"proguanil"']
standardized_treatments:  ['chloroquine', 'mefloquine', 'atovaquone', 'proguanil']
original treatments:  ['"Clofazimine"', '"dapsone"', '"Hydroquinone"', '"griseofulvin"', '"isoniazid"']
standardized_treatments:  ['clofazimine', 'dapsone', 'hydroquinone', 'griseofulvin', 'isoniazid']
original treatments:  ['"Crisaborole"', '"abrocitinib"', '"upadacitinib"', '"ruxolitinib"', '"dupilumab"', '"tralokinumab"', '"corticosteroid medications"', '"oral steroids"']
standardized_treatments:  ['crisaborole', 'abrocitinib', 'upadacitinib', 'ruxolitinib', 'dupilumab', 'tralokinumab', 'corticosteroids', 'corticosteroids']
original treatments:  ['"Minocycline"', '"ibuprofen"', '"penicillin"', '"Vitamin C"']
standardized_treatments:  ['tetracyclines', 'ibuprofen', 'antibiotics', 'vitamin c']
original treatments:  ['"Minocycline"', '"macrolide class antibiotics"', '"tetracycline"', '"doxycycline"', '"cefdinir"']
standardized_treatments:  ['tetracyclines', 'azithromycin', 'tetracyclines', 'tetracyclines', 'cefdinir']
original treatments:  ['"Podophyllin"', '"Imiquimod"', '"5-FU"', '"various acids"']
standardized_treatments:  ['podophyllin', 'imiquimod', '5-fluorouracil', 'alpha-hydroxy acid']
original treatments:  ['"antibiotics"']
standardized_treatments:  ['antibiotics']
original treatments:  ['"antibiotics"', '"steroid gels"']
standardized_treatments:  ['antibiotics', 'corticosteroids']
original treatments:  ['"antibiotics"', '"topical medications"', '"bleach"', '"antiviral medications"']
standardized_treatments:  ['antibiotics', 'medications', 'bleach', 'antiviral medications']

100%|██████████| 1/1 [00:00<00:00, 8176.03it/s]

##### Cast treatments from STRING to ARRAY<STRING>

In [129]:
%%bigquery
SELECT
  -- Use JSON_EXTRACT_ARRAY to convert the cleaned string into an array
  JSON_EXTRACT_ARRAY(treatments) AS treatments
FROM
  `skincare_products_stg.dermatologic_disease`

Query is running:   0%|          |

Downloading:   0%|          |

                                            treatments
0                                                   []
1                                                   []
2                                                   []
3                                                   []
4                                                   []
..                                                 ...
365  ["corticosteroids", "pimecrolimus", "tacrolimu...
366  ["tetracyclines", "tetracyclines", "corticoste...
367  ["methotrexate", "acitretin", "cyclosporine", ...
368  ["tetracyclines", "salicylic acid", "benzoyl p...
369  ["fexofenadine", "loratidine", "cetirizine", "...

[370 rows x 1 columns]

#### Replace `N/A` and `Not applicable` with NULL

In [130]:
%%bigquery
select
case
  when causes in ('N/A', 'Not applicable') then null
  else causes
  end as causes,
from skincare_products_stg.dermatologic_disease;

Query is running:   0%|          |

Downloading:   0%|          |

                                                causes
0    The cause of Spitz nevus is currently unknown,...
1    A normal physiologic response of the newborn t...
2    Dermoscopy is used to evaluate both benign and...
3    The exact cause of psoriasis is unknown, but i...
4    Unwanted hair growth can be caused by several ...
..                                                 ...
365  The exact cause of DLE is unknown, but it is t...
366  An autoimmune disorder where the body's immune...
367  Psoriasis is triggered by factors such as bact...
368  The disease is spread by ticks that acquire th...
369  Hives are often caused by infections, viruses,...

[370 rows x 1 columns]

#### Putting it all together

In [131]:
%%bigquery
select name, physical_description,
case
  when causes in ('N/A', 'Not applicable') then null
  else causes
  end as causes,
JSON_EXTRACT_ARRAY(treatments) as treatments,
_data_source,
_load_time
from skincare_products_stg.dermatologic_disease;

Query is running:   0%|          |

Downloading:   0%|          |

,name,physical_description,causes,treatments,_data_source,_load_time
0,Spitz Nevus,"Spitz nevus is typically a solitary, round, fi...","The cause of Spitz nevus is currently unknown,...",[],dermatologic_disease,2024-09-25 02:15:27.599878+00:00
1,Cutis Marmorata,"A red and/or blue, lacy pattern appears on the...",A normal physiologic response of the newborn t...,[],dermatologic_disease,2024-09-25 02:15:27.599878+00:00
2,Dermoscopy,Dermoscopy is a non-invasive technique used to...,Dermoscopy is used to evaluate both benign and...,[],dermatologic_disease,2024-09-25 02:15:27.599878+00:00
3,Psoriasis,"Psoriasis is a skin condition that causes red,...","The exact cause of psoriasis is unknown, but i...",[],dermatologic_disease,2024-09-25 02:15:27.599878+00:00
4,Unwanted Hair Growth,Unwanted hair growth occurs when hair grows in...,Unwanted hair growth can be caused by several ...,[],dermatologic_disease,2024-09-25 02:15:27.599878+00:00
...,...,...,...,...,...,...
365,Discoid Lupus Erythematosus,Discoid lupus erythematosus (DLE) is a chronic...,"The exact cause of DLE is unknown, but it is t...","[""corticosteroids"", ""pimecrolimus"", ""tacrolimu...",dermatologic_disease,2024-09-25 02:15:27.599878+00:00
366,Bullous Pemphigoid,A chronic blistering skin condition that can r...,An autoimmune disorder where the body's immune...,"[""tetracyclines"", ""tetracyclines"", ""corticoste...",dermatologic_disease,2024-09-25 02:15:27.599878+00:00
367,Psoriasis,Psoriasis is a common skin condition character...,Psoriasis is triggered by factors such as bact...,"[""methotrexate"", ""acitretin"", ""cyclosporine"", ...",dermatologic_disease,2024-09-25 02:15:27.599878+00:00
368,Lyme Disease,"Flu-like symptoms, fever, muscle aches, joint ...",The disease is spread by ticks that acquire th...,"[""tetracyclines"", ""salicylic acid"", ""benzoyl p...",dermatologic_disease,2024-09-25 02:15:27.599878+00:00
369,Urticaria (Hives),"Urticaria, also known as hives, are pink welts...","Hives are often caused by infections, viruses,...","[""fexofenadine"", ""loratidine"", ""cetirizine"", ""...",dermatologic_disease,2024-09-25 02:15:27.599878+00:00

#### Apply changes to staging table

In [132]:
%%bigquery
create or replace table skincare_products_stg.dermatologic_disease as
  select name, physical_description,
  case
    when causes in ('N/A', 'Not applicable') then null
    else causes
    end as causes,
  JSON_EXTRACT_ARRAY(treatments) as treatments,
  _data_source,
  _load_time
  from skincare_products_stg.dermatologic_disease;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

### `sephora_product` table

#### Convert `limited_edition`, `new`, `online_only`, `out_of_stock`, and `sephora_exclusive` from Integer to Bool

In [28]:
%%bigquery
select
  safe_cast(limited_edition as BOOLEAN) as limited_edition,
  safe_cast(`new` as BOOLEAN) as `new`,
  safe_cast(online_only as BOOLEAN) as online_only,
  safe_cast(out_of_stock as BOOLEAN) as out_of_stock,
  safe_cast(sephora_exclusive as BOOLEAN) as sephora_exclusive
from skincare_products_raw.sephora_product

Query is running:   0%|          |

Downloading:   0%|          |

      limited_edition    new  online_only  out_of_stock  sephora_exclusive
0               False  False         True          True               True
1               False  False         True         False              False
2               False  False         True          True               True
3               False  False        False         False               True
4               False   True         True         False              False
...               ...    ...          ...           ...                ...
8489            False  False         True         False              False
8490            False  False        False         False              False
8491            False  False         True         False              False
8492            False   True         True          True               True
8493             True  False         True         False              False

[8494 rows x 5 columns]

#### Rename ambigious fields

In [29]:
%%bigquery
select
  `new` as new_product,
  child_count as variation_count,
  child_max_price as variation_max_price,
  child_min_price as variation_min_price,
  highlights as feature_highlights
from skincare_products_raw.sephora_product

Query is running:   0%|          |

Downloading:   0%|          |

,new_product,variation_count,variation_max_price,variation_min_price,feature_highlights
0,0,0,NaN,NaN,"['Good for: Dryness', 'Clean at Sephora', 'Hyd..."
1,0,0,NaN,NaN,"['Good for: Dryness', 'Clean at Sephora', 'Hyd..."
2,0,0,NaN,NaN,"['Hydrating', 'Good for: Frizz', 'Good for: Dr..."
3,0,0,NaN,NaN,"['Vegan', 'Good for: Loss of firmness', 'Good ..."
4,1,0,NaN,NaN,"['Vegan', 'Good for: Loss of firmness', 'Plump..."
...,...,...,...,...,...
8489,0,0,NaN,NaN,"['allure 2022 Best of Beauty Award Winner', 'C..."
8490,0,0,NaN,NaN,None
8491,0,0,NaN,NaN,"['Stick Formula', 'Floral Scent', 'Alcohol Fre..."
8492,1,0,NaN,NaN,"['Vegan', 'Good for: Dullness/Uneven Texture',..."
8493,0,0,NaN,NaN,"['Without Mineral Oil', 'Without Phthalates', ..."

#### Split `size` into imperial_size, metric_size, and other_size

In [58]:
%%bigquery
select distinct
  case
    when size not like '%oz%'
      and size not like '%g%'
      and size not like '%mL%'
      and size not like '%ml%'
      and size not like '%in%'
      and size not like '%inches%'
      and size not like '%Inches%'
      and size not like '%/%'
    then size
    else null
  end as other_size,
  case
    when contains_substr(size, '/') then split(size, '/')[SAFE_OFFSET(0)]
    when size like '%oz%'
      or size like '%inches%'
      or size like '%Inches%'
    then size
    else null
  end as imperial_size,
  case
    when contains_substr(size, '/') then split(size, '/')[SAFE_OFFSET(1)]
    when size like '%g%'
      or size like '%mL%'
      or size like '%ml%'
    then size
    else null
  end as metric_size,
from skincare_products_raw.sephora_product

Query is running:   0%|          |

Downloading:   0%|          |

     other_size imperial_size                  metric_size
0          None          None                         None
1          None    8 x .02 oz                        .80 g
2       1" wand          None                         None
3          None  2 x .032 oz                         0.9 g
4          None          2 oz                        60 mL
...         ...           ...                          ...
2046       None      0.33 oz    9.8 mL eau de parfum spray
2047       None         .33oz                         10mL
2048       None        0.3 oz                       7.5 mL
2049       None      0.34 oz           10 mL Perfume Spray
2050       None          2oz                          59mL

[2051 rows x 3 columns]

#### Extracting color from variation_type and variation_value

In [75]:
%%bigquery
select variation_type,
  case when variation_type like '%Color%' then variation_value else null
  end as color
from skincare_products_raw.sephora_product
group by variation_type, variation_value
order by variation_type

Query is running:   0%|          |

Downloading:   0%|          |

     variation_type                                             color
0              None                                              None
1             Color                                             Lilac
2             Color                                             Taupe
3             Color                                      Medium Brown
4             Color  Tease Satin Lipstick + Baby Roses Mini Lip Liner
...             ...                                               ...
2814           Type                                              None
2815           Type                                              None
2816           Type                                              None
2817           Type                                              None
2818           Type                                              None

[2819 rows x 2 columns]

#### Putting it all together

In [133]:
%%bigquery
select
  product_id,
  product_name,
  brand_id,
  brand_name,
  loves_count,
  rating,
  reviews,
  case
    when size not like '% oz%'
      and size not like '% g%'
      and size not like '% mL%'
      and size not like '% ml%'
      and size not like '% in%'
      and size not like '% inches%'
      and size not like '% Inches%'
      and size not like '%/%'
    then size
    else null
  end as other_size,
  case
    when contains_substr(size, '/') then split(size, '/')[SAFE_OFFSET(0)]
    when size like '% oz%'
      or size like '% inches%'
      or size like '% Inches%'
    then size
    else null
  end as imperial_size,
  case
    when contains_substr(size, '/') then split(size, '/')[SAFE_OFFSET(1)]
    when size like '% g%'
      or size like '% mL%'
      or size like '% ml%'
    then size
    else null
  end as metric_size,
  case
    when variation_type like '%Color%' then variation_value
    else null
  end as color,
  child_count as variation_count,
  child_max_price as variation_max_price,
  child_min_price as variation_min_price,
  JSON_EXTRACT_ARRAY(ingredients) as ingredients,
  price_usd,
  value_price_usd,
  sale_price_usd,
  safe_cast(limited_edition as BOOLEAN) as limited_edition,
  safe_cast(`new` as BOOLEAN) as new_product,
  safe_cast(online_only as BOOLEAN) as online_only,
  safe_cast(out_of_stock as BOOLEAN) as out_of_stock,
  safe_cast(sephora_exclusive as BOOLEAN) as sephora_exclusive,
  highlights as feature_highlights,
  primary_category,
  secondary_category,
  tertiary_category,
  _data_source,
  _load_time
from skincare_products_raw.sephora_product;

Query is running:   0%|          |

Downloading:   0%|          |

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,other_size,imperial_size,metric_size,...,new_product,online_only,out_of_stock,sephora_exclusive,feature_highlights,primary_category,secondary_category,tertiary_category,_data_source,_load_time
0,P476418,African Beauty Butter Mini Gift Set,6471,54 Thrones,7526,3.5610,41,None,None,None,...,False,True,True,True,"['Good for: Dryness', 'Clean at Sephora', 'Hyd...",Bath & Body,Value & Gift Sets,None,sephora_product,2024-09-25 02:15:33.136361+00:00
1,P476417,African Beauty Butter Collection Deluxe Tin,6471,54 Thrones,3741,4.2273,22,None,None,None,...,False,True,False,False,"['Good for: Dryness', 'Clean at Sephora', 'Hyd...",Bath & Body,Value & Gift Sets,None,sephora_product,2024-09-25 02:15:33.136361+00:00
2,P473151,Mini Baomint Deluxe Travel Kit,6321,adwoa beauty,4559,4.7283,173,None,None,None,...,False,True,True,True,"['Hydrating', 'Good for: Frizz', 'Good for: Dr...",Hair,Value & Gift Sets,None,sephora_product,2024-09-25 02:15:33.136361+00:00
3,P500716,10 Day Results Kit,6018,Algenist,3206,4.8023,258,None,None,None,...,False,False,False,True,"['Vegan', 'Good for: Loss of firmness', 'Good ...",Skincare,Value & Gift Sets,None,sephora_product,2024-09-25 02:15:33.136361+00:00
4,P504443,Plump Pout Duo,6018,Algenist,522,3.0000,1,None,None,None,...,True,True,False,False,"['Vegan', 'Good for: Loss of firmness', 'Plump...",Skincare,Value & Gift Sets,None,sephora_product,2024-09-25 02:15:33.136361+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8489,P481959,Wake the F*ck Up Deodorant,8007,By Rosie Jane,7318,3.9773,44,None,2oz,59mL,...,False,True,False,False,"['allure 2022 Best of Beauty Award Winner', 'C...",Bath & Body,Body Care,Deodorant & Antiperspirant,sephora_product,2024-09-25 02:15:33.136361+00:00
8490,P473115,BLEU DE CHANEL All-over Spray,1065,CHANEL,998,NaN,<NA>,None,5 oz,148 mL,...,False,False,False,False,None,Bath & Body,Body Care,Deodorant & Antiperspirant,sephora_product,2024-09-25 02:15:33.136361+00:00
8491,P503730,Cashmere Mist Aluminum Free/Alcohol Free Deodo...,3491,Donna Karan,3171,3.3333,15,None,1.7 oz,50 mL,...,False,True,False,False,"['Stick Formula', 'Floral Scent', 'Alcohol Fre...",Bath & Body,Body Care,Deodorant & Antiperspirant,sephora_product,2024-09-25 02:15:33.136361+00:00
8492,P504143,Rio Deo Aluminum-Free Deodorant Cheirosa '40,6145,Sol de Janeiro,20982,3.4444,63,None,2 oz,57 g,...,True,True,True,True,"['Vegan', 'Good for: Dullness/Uneven Texture',...",Bath & Body,Body Care,Deodorant & Antiperspirant,sephora_product,2024-09-25 02:15:33.136361+00:00
8493,P501007,Pumpkin Chai Liquid Soap,7025,NEST New York,550,NaN,<NA>,None,10 oz,300 mL,...,False,True,False,False,"['Without Mineral Oil', 'Without Phthalates', ...",Bath & Body,Body Care,Hand Sanitizer & Hand Soap,sephora_product,2024-09-25 02:15:33.136361+00:00

#### Create staging table

In [134]:
%%bigquery
create or replace table skincare_products_stg.sephora_product as
  select
    product_id,
    product_name,
    brand_id,
    brand_name,
    loves_count,
    rating,
    reviews,
    case
      when size not like '% oz%'
        and size not like '% g%'
        and size not like '% mL%'
        and size not like '% ml%'
        and size not like '% in%'
        and size not like '% inches%'
        and size not like '% Inches%'
        and size not like '%/%'
      then size
      else null
    end as other_size,
    case
      when contains_substr(size, '/') then split(size, '/')[SAFE_OFFSET(0)]
      when size like '% oz%'
        or size like '% inches%'
        or size like '% Inches%'
      then size
      else null
    end as imperial_size,
    case
      when contains_substr(size, '/') then split(size, '/')[SAFE_OFFSET(1)]
      when size like '% g%'
        or size like '% mL%'
        or size like '% ml%'
      then size
      else null
    end as metric_size,
    case
      when variation_type like '%Color%' then variation_value
      else null
    end as color,
    child_count as variation_count,
    child_max_price as variation_max_price,
    child_min_price as variation_min_price,
    JSON_EXTRACT_ARRAY(ingredients) as ingredients,
    price_usd,
    value_price_usd,
    sale_price_usd,
    safe_cast(limited_edition as BOOLEAN) as limited_edition,
    safe_cast(`new` as BOOLEAN) as new_product,
    safe_cast(online_only as BOOLEAN) as online_only,
    safe_cast(out_of_stock as BOOLEAN) as out_of_stock,
    safe_cast(sephora_exclusive as BOOLEAN) as sephora_exclusive,
    highlights as feature_highlights,
    primary_category,
    secondary_category,
    tertiary_category,
    _data_source,
    _load_time
  from skincare_products_raw.sephora_product

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

#### Standardize Ingredient using LLM

##### Fetch ingredients from `sephora_product` table

In [37]:
%%bigquery
WITH flattened_ingredients AS (
  -- Flatten the array into individual rows and split the ingredient strings
  SELECT
    LOWER(TRIM(ingredient_part)) AS ingredient -- Convert to lowercase and trim spaces
  FROM
    skincare_products_stg.sephora_product,
    UNNEST(ingredients) AS ingredient, -- Unnest the array into individual strings
    UNNEST(SPLIT(ingredient, ',')) AS ingredient_part -- Split each string by comma and unnest into individual parts
  WHERE
    ingredients IS NOT NULL
)
-- Select distinct ingredients and sort them alphabetically
SELECT DISTINCT ingredient
FROM flattened_ingredients
ORDER BY ingredient;

Query is running:   0%|          |

Downloading:   0%|          |

                                        ingredient
0
1                                                "
2                                               ""
3                                "#12103/a alcohol
4                                   "#14881/a talc
...                                            ...
18814                    zymomonas ferment extract
18815  ¬glycyrrhiza glabra (licorice) root extract
18816                               α-phellandrene
18817                          ψ hydrolyzed quinoa
18818                 ‎acorus calamus (sweet flag)

[18819 rows x 1 columns]

##### (LONG RUNTIME) Generate standardized replacements using LLM

In [39]:
import json
import pandas_gbq
import numpy as np
import vertexai
from vertexai.generative_models import GenerativeModel, Part, HarmCategory, HarmBlockThreshold
from google.cloud import bigquery
import pandas as pd
import ast


project_id = "segfault-434120"
region = "us-central1"
dataset_id = "skincare_products_stg"
model_name = "gemini-1.5-flash-001"
prompt = """Go through this list of ingredients and look for ingredients that have similar meanings, but were given different names.
For example, '5-FU' and '5-fluorouracil' have similar meanings and 'alpha-hydroxy acid' and 'alpha hydroxyacids' have similar meanings.
Suggest a standard ingredient name, mapping the current one to the new one.
The standard name should not have any arbitrary special characters.
For example, 'ψ hydrolyzed quinoa' should instead be 'hydrolyzed quinoa'.
Some names are product names rather than ingredient names, so map them to an empty string.
For example, 'your skin but better setting spray', 'you’re my sol mate', and 'witch hazel & yucca deep hydrating shampoo' should all be mapped to ''.
Return the list of original ingredient names along with their new ingredient names.
Format the results as a json object with the schema: current_ingredient:string, new_ingredient:string.
Do not include any unchanged ingredient names with your answer.
Do not include an explanation with your answer.
"""

reformat_prompt = """You are given the following JSON data which contains formatting issues and errors.
Your task is to correct the format and return a valid JSON object.
Make sure all necessary commas, quotes, and braces are correctly placed.
For example, all key-value pairs must follow the structure "key string":"value string" within the json brackets.
Do not confuse a : inside a string with the : separating the key-value pair of the dictionary.
For example, {"your skin but better setting spray+:""your skin but better setting spray"} is missing a colon between the key and value pair.
Format the results as a json object with the schema: current_ingredient:string, new_ingredient:string.
Do not change the actual data values or structure, only correct the formatting errors.
Do not include an explanation with your answer.
"""

product_ingredients_sql = """
WITH flattened_ingredients AS (
  -- Flatten the array into individual rows and split the ingredient strings
  SELECT
    LOWER(TRIM(ingredient_part)) AS ingredient -- Convert to lowercase and trim spaces
  FROM
    skincare_products_stg.sephora_product,
    UNNEST(ingredients) AS ingredient, -- Unnest the array into individual strings
    UNNEST(SPLIT(ingredient, ',')) AS ingredient_part -- Split each string by comma and unnest into individual parts
  WHERE
    ingredients IS NOT NULL
)
-- Select distinct ingredients and sort them alphabetically
SELECT DISTINCT ingredient
FROM flattened_ingredients
ORDER BY ingredient;
"""

bq_client = bigquery.Client()
ingredient_rows = bq_client.query_and_wait(product_ingredients_sql)

ingredient_list = []
for row in ingredient_rows:
    ingredient_list.append(row["ingredient"])


replacements = {} # will store the new ingredients

# Find replacements in chunks
CHUNKS = 70
ingredient_list_chunks = np.array_split(ingredient_list, CHUNKS)
for i, chunk in enumerate(ingredient_list_chunks):
  ingredient_str = '\n'.join(chunk)
  #print("ingredient_str:", ingredient_str)

  vertexai.init(project=project_id, location=region)
  model = GenerativeModel(model_name)
  try:
    resp = model.generate_content(contents=[ingredient_str, prompt], safety_settings={
                  HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                  HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                  HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                  HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
              })
    resp_text = resp.text.replace("```json", "").replace("```", "").replace("\n", "")
    print(resp_text)
  except ValueError as ve:
    print(f"Content moderation error on chunk {i}: {ve}")
    continue  # Skip this chunk if moderation blocks the response

  max_retries = 3
  retry_count = 0
  status = ""
  success = False

  while retry_count < max_retries and not success:
      try:
          ingredients = json.loads(resp_text)
          success = True  # Exit the loop if parsing is successful
      except:
          print("INVALID JSON, reformatting...")

          # Attempt to fix JSON
          status = f"STATUS: This is reformatting attempt #{retry_count}. Make sure you aren't overlooking JSON errors. There may be more than one."
          try:
            resp = model.generate_content(contents=[status, resp_text, reformat_prompt], safety_settings={
                HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
            })
            resp_text = resp.text.replace("```json", "").replace("```", "").replace("\n", "")
            print(resp_text)

            # Attempt to load the reformatted JSON again
            try:
                ingredients = json.loads(resp_text)
                success = True  # Exit the loop if parsing is successful
            except:
                print(f"Retry {retry_count + 1} failed.")
                retry_count += 1
          except:
            print("Failed to generate JSON. Content Moderation Error")
            retry_count += 1



  if not success:
      print(f"Failed to parse JSON after {retry_count + 1} retries. Skipping chunk {i}")
  print(type(ingredients))


  # ingredients can be either a dictionary or list type (depending on what LLM decides to do!)
  if type(ingredients) == dict:
      for old, new in ingredients.items():
          if old == new:
              continue
          else:
              replacements[old] = new

  if type(ingredients) == list:
      for cat_entry in ingredients:
          if cat_entry['current_ingredient'] == cat_entry['new_ingredient']:
              continue
          else:
              replacements[cat_entry['current_ingredient']] = cat_entry['new_ingredient']


# lowercase all ingredient names
replacements = {key.lower(): value.lower() for key, value in replacements.items()}
print("replacements:", replacements)

{"(+/-) may contain/peut contenir: red 40 lake (ci 16035)": "red 40 lake","(+/-) may contain/peut contenir: iron oxides (ci 77491": "iron oxides","(+/-) may contain/peut contenir: iron oxides (ci 77492": "iron oxides","(+/-) may contain/peut contenir: iron oxides (ci 77492": "iron oxides","(ci 15850)": "red 6","(ci 75470)": "red 7","(ci 77163)": "bismuth oxychloride","(ci 77491)": "iron oxides","(ci 77499 / iron oxides)": "iron oxides","(ci 77499)": "iron oxides","(ci 77499)  ": "iron oxides","(ci 77510)": "ferric ferrocyanide","(ci 77742)].": "ultramarines","(ci 77891 (titanium dioxide)": "titanium dioxide","(ci 77891)": "titanium dioxide","(fragrance)": "parfum","(natural)": "","(only 0.005% glycerin).": "glycerin","(pisum sativum (pea) extract)": "pea extract","(re)setting mist:": "","(±) may contain/peut contenir: copper powder (ci 77400)": "copper powder","(±) may contain/peut contenir: iron oxides (ci 77492": "iron oxides","(±) may contain/peut contenir: iron oxides (ci 77492": "iron oxides","+retinol eye cream:": "","+retinol vita c serum:": "","+retinol vitamin c moisturizer:": "","10% azelaic acid booster:": "","10% benzoyl peroxide acne cleanser:": "","10% glycolic acid": "glycolic acid","10% niacinamide night mask:": "","10+10 more-sturizer:": "","100% brazilian rose quartz.": "","100% cotton fiber.": "","100% cotton.": "","100% cruelty-free synthetic bristles.": "","100% high-grade (6a) long-fiber mulberry silk with a thickness of 22 momme.": "","100% macadamia-oil concentrate fragrance free for hair and body:": "","100% mulberry silk outer and inner layers": "","100% natural": "","100% oeko-tex 100 certified viscose rayon.": "","100% organic cold-pressed rose hip seed oil:": "","100% polyester.": "","100% pure soy wax with a cotton wick.": "","100% pure tea tree oil.": "","100% slipsilk (exclusive of elastic and crystals)": "","100% unrefined sclerocraya birrea (marula) kernel oil.": "","100% vegan and cruelty free.": "","10eicosanedioate/tetradecanedioate": "10-eicosanedioate/tetradecanedioate","17200 (red 33 lake)": "red 33 lake","2-hexanediol.": "hexylene glycol","2-methyl-3-(p-isopropylphenyl)propionaldehyde": "p-isopropylphenyl)","24/7 glide-on eye pencil:": "","24k gold mask pure luxury lift & firm:": "","24k:": "","25 miracle milk heat protectant leave-in conditioner:": "","3 hexenyl benzoate": "hexenyl benzoate","4-tert-butylcyclohexyl acetate": "tert-butylcyclohexyl acetate","42090 (blue 1).": "blue 1","42090)": "blue 1","45 second top coat with retinol:": "","5 lake (ci 19140)": "red 5 lake","5% benzoyl peroxide acne spot treatment:": "","560326 08 alcohol": "alcohol","70% alcohol": "alcohol","75% vol. alcohol denat.": "alcohol","77007)": "ultramarines","77491": "iron oxides","77499 (iron oxides).": "iron oxides","77499)": "iron oxides","77510)": "ferric ferrocyanide","77742)].": "ultramarines","77891 (titanium dioxide)": "titanium dioxide","77891)": "titanium dioxide","78% vol. alcohol denat.": "alcohol","79% alcohol by volume.": "alcohol","875650 18 alcohol": "alcohol","875655 10 alcohol": "alcohol","[+/- iron oxides (ci 77499)].": "iron oxides","[+/- red 6 (ci 15850)": "red 6","[+/- titanium dioxide (ci 77891)": "titanium dioxide","[may contain / peut contenir: ci 77491": "iron oxides","[may contain : ci 77491": "iron oxides","[may contain ci 77891 / titanium dioxide": "titanium dioxide","a+ high-dose retinoid serum:": "","a+ high-dose retinol serum:": "","a1": "","a1": "","a1:": "","a2": "","a2:": "","a3": "","a3": "","a3:": "","a4": "","a4:": "","a5": "","a5:": "","abeille royale advanced youth watery oil:": "","abeille royale anti-aging double r advanced serum:": "","abeille royale anti-aging fortifying lotion toner:": "","absolutely:": "","abundance:": "","acacia gum": "acacia Senegal gum","accepting:": "","acetate": "acetate","acetone": "acetone","acetyl cedrene": "acetyl cedrene","acid": "acid","acne clearing wash:": "","acne solutions cleansing foam:": "","acne solutions clinical clearing gel:": "","acne+ 2% bha acne spot treatment:": "","acne+ 2% bha cleanser:": "","acondicionador de cupuacu & castor:": "","acqua di gioia:": "","acqua neroli:": "","acrylate": "acrylate","acrylate copolymer.": "acrylate copolymer","acrylates/ethylhexl": "acrylates/ethylhexyl acrylate","acryloyldimethyl taurate copolymer": "acryloyldimethyl taurate copolymer","active blast concentrated collagen daily treatment:": "","active cartridge concentrate for pores & uneven texture:": "","active purple pore-refining antioxidant mask:": "","activist:": "","adaptogen activated mist:": "","adaptogen deep moisture cream:": "","adore me:": "","adriatic:": "","advanced clean dry shampoo:": "","advanced génifique eye cream:": "","advanced génifique face serum:": "","advanced génifique night cream:": "","advanced génifique yeux light pearl:": "","advanced génifique youth activating serum:": "","advanced night repair eye supercharged gel-creme synchronized multi-recovery:": "","advanced night repair synchronized multi-recovery complex:": "","adwoa blue tansy reparative mask water (aqua)": "water","aesthetic:": "","affair: mica": "mica","affinity 476sf:": "","affirmation:": "","affogato:": "","after dusk:": "","after hours:": "","afterglow lip balm in dolce vita:": "","afterglow lip balm in orgasm:": "","afterglow lip balm orgasm: hydrogenated polyisobutene": "hydrogenated polyisobutene","afterglow lip shine:": "","aiko 475cm.:": "","airy:": "","alaria esculenta extract": "alaria esculenta extract","alba bark extract": "alba bark extract","alcium sodium borosilicate": "calcium sodium borosilicate","alcohol": "alcohol","alcohol  denat.": "alcohol","alcohol (organic)": "alcohol","alcohol denat": "alcohol","alcohol denat (sd alcohol 39-c)": "alcohol","alcohol denat.": "alcohol","alcohol denat. (sd alcohol 39-c .)": "alcohol","alcohol denat. (sd alcohol 39-c)": "alcohol","alcohol denat. (sd alcohol 39-c.)": "alcohol","alcohol denat. (sd alcohol 39c)": "alcohol","alcohol denat. 75% vol.": "alcohol","alcohol denat. parfum (fragrance)": "alcohol","alcohol denat./ sd alcohol 40-b": "alcohol","alcohol denat./sd alcohol 40-b": "alcohol","aleurites fordi oil copolymer": "aleurites fordi oil copolymer","aleurites moluccana seed oil": "aleurites moluccana seed oil","algae (seaweed) extract": "algae extract","algae extract": "algae extract","algae) extract": "algae extract","algal oil": "algal oil","alien goddess:": "","alien:": "","all - may contain (+/-) ci 16035 (red 40 lake)": "red 40 lake","all about clean 2-in-1 cleansing + exfoliating jelly:": "","all about clean liquid facial soap:": "","all about eyes eye cream:": "","all about shadow palette:": "","all diamond shades contain:": "","all original shades except dominique and krystal contain:": "","all other shades:": "","all shades (+/-) may contain/peut contenir: iron oxides (ci 77491": "iron oxides","all shades contain:": "","all shades:": "","all tint shades contain:": "","all voluspa candles are vegan and contain a clean-burning coconut wax blend": "","all-in-one nourishing eye cream:": "","all-in-one nourishing face cream:": "","all-in-one super nutrient face oil:": "","all-natural coconut and beeswax blend. paraffin-free. 100% braided cotton wick.": "","all-natural coconut-beeswax blend. paraffin-free. 100% braided cotton wick.": "","all-over wash for face": "","allantoin": "allantoin","allantoin: soothes the look of irritation and redness while supporting skin’s health.": "allantoin",": caprylic/capric triglyceride": "caprylic/capric triglyceride",": rayon": "rayon","a1": "","a1": "","a1:": "","a2": "","a2:": "","a3": "","a3": "","a3:": "","a4": "","a4:": "","a5": "","a5:": "","abeille royale advanced youth watery oil:": "","abeille royale anti-aging double r advanced serum:": "","abeille royale anti-aging fortifying lotion toner:": "","ablaze:": "","absolutely:": "","abundance:": "","acacia gum": "acacia Senegal gum","accepting:": "","aceite de moska:": "","acetate": "acetate","acetone": "acetone","acetyl cedrene": "acetyl cedrene","acid": "acid","acne clearing wash:": "","acne solutions cleansing foam:": "","acne solutions clinical clearing gel:": "","acne+ 2% bha acne spot treatment:": "","acne+ 2% bha cleanser:": "","acondicionador de cupuacu & castor:": "","acqua di gioia:": "","acqua neroli:": "","acrylate": "acrylate","acrylate copolymer.": "acrylate copolymer","acrylates/ethylhexl": "acrylates/ethylhexyl acrylate","acryloyldimethyl taurate copolymer": "acryloyldimethyl taurate copolymer","active blast concentrated collagen daily treatment:": "","active cartridge concentrate for pores & uneven texture:": "","active purple pore-refining antioxidant mask:": "","activist:": "","adaptogen activated mist:": "","adaptogen deep moisture cream:": "","adore me:": "","adriatic:": "","advanced clean dry shampoo:": "","advanced génifique eye cream:": "","advanced génifique face serum:": "","advanced génifique night cream:": "","advanced génifique yeux light pearl:": "","advanced génifique youth activating serum:": "","advanced night repair eye supercharged gel-creme synchronized multi-recovery:": "","advanced night repair synchronized multi-recovery complex:": "","adwoa blue tansy reparative mask water (aqua)": "water","aesthetic:": "","affair: mica": "mica","affinity 476sf:": "","affirmation:": "","affogato:": "","after dusk:": "","after hours:": "","afterglow lip balm in dolce vita:": "","afterglow lip balm in orgasm:": "","afterglow lip balm orgasm: hydrogenated polyisobutene": "hydrogenated polyisobutene","afterglow lip shine:": "","aiko 475cm.:": "","airy:": "","alaria esculenta extract": "alaria esculenta extract","alba bark extract": "alba bark extract","alcium sodium borosilicate": "calcium sodium borosilicate","alcohol": "alcohol","alcohol  denat.": "alcohol","alcohol (organic)": "alcohol","alcohol denat": "alcohol","alcohol denat (sd alcohol 39-c)": "alcohol","alcohol denat.": "alcohol","alcohol denat. (sd alcohol 39-c .)": "alcohol","alcohol denat. (sd alcohol 39-c)": "alcohol","alcohol denat. (sd alcohol 39-c.)": "alcohol","alcohol denat. (sd alcohol 39c)": "alcohol","alcohol denat. 75% vol.": "alcohol","alcohol denat. parfum (fragrance)": "alcohol","alcohol denat./ sd alcohol 40-b": "alcohol","alcohol denat./sd alcohol 40-b": "alcohol","aleurites fordi oil copolymer": "aleurites fordi oil copolymer","aleurites moluccana seed oil": "aleurites moluccana seed oil","algae (seaweed) extract": "algae extract","algae extract": "algae extract","algae) extract": "algae extract","algal oil": "algal oil","alien goddess:": "","alien:": "","all - may contain (+/-) ci 16035 (red 40 lake)": "red 40 lake","all about clean 2-in-1 cleansing + exfoliating jelly:": "","all about clean liquid facial soap:": "","all about eyes eye cream:": "","all about shadow palette:": "","all diamond shades contain:": "","all original shades except dominique and krystal contain:": "","all other shades:": "","all shades (+/-) may contain/peut contenir: iron oxides (ci 77491": "iron oxides","all shades contain:": "","all shades:": "","all tint shades contain:": "","all voluspa candles are vegan and contain a clean-burning coconut wax blend": "","all-in-one nourishing eye cream:": "","all-in-one nourishing face cream:": "","all-in-one super nutrient face oil:": "","all-natural coconut and beeswax blend. paraffin-free. 100% braided cotton wick.": "","all-natural coconut-beeswax blend. paraffin-free. 100% braided cotton wick.": "","all-over wash for face": "","allantoin": "allantoin","allantoin: soothes the look of irritation and redness while supporting skin’s health.": "allantoin",": caprylic/capric triglyceride": "caprylic/capric triglyceride",": rayon": "rayon","a1": "","a1": "","a1:": "","a2": "","a2:": "","a3": "","a3": "","a3:": "","a4": "","a4:": "","a5": "","a5:": "","abeille royale advanced youth watery oil:": "","abeille royale anti-aging double r advanced serum:": "","abeille royale anti-aging fortifying lotion toner:": "","ablaze:": "","absolutely:": "","abundance:": "","acacia gum": "acacia Senegal gum","accepting:": "","aceite de moska:": "","acetate": "acetate","acetone": "acetone","acetyl cedrene": "acetyl cedrene","acid": "acid","acne clearing wash:": "","acne solutions cleansing foam:": "","acne solutions clinical clearing gel:": "","acne+ 2% bha acne spot treatment:": "","acne+ 2% bha cleanser:": "","acondicionador de cupuacu & castor:": "","acqua di gioia:": "","acqua neroli:": "","acrylate": "acrylate","acrylate copolymer.": "acrylate copolymer","acrylates/ethylhexl": "acrylates/ethylhexyl acrylate","acryloyldimethyl taurate copolymer": "acryloyldimethyl taurate copolymer","active blast concentrated collagen daily treatment:": "","active cartridge concentrate for pores & uneven texture:": "","active purple pore-refining antioxidant mask:": "","activist:": "","adaptogen activated mist:": "","adaptogen deep moisture cream:": "","adore me:": "","adriatic:": "","advanced clean dry shampoo:": "","advanced génifique eye cream:": "","advanced génifique face serum:": "","advanced génifique night cream:": "","advanced génifique yeux light pearl:": "","advanced génifique youth activating serum:": "","advanced night repair eye supercharged gel-creme synchronized multi-recovery:": "","advanced night repair synchronized multi-recovery complex:": "","adwoa blue tansy reparative mask water (aqua)": "water","aesthetic:": "","affair: mica": "mica","affinity 476sf:": "","affirmation:": "","affogato:": "","after dusk:": "","after hours:": "","afterglow lip balm in dolce vita:": "","afterglow lip balm in orgasm:": "","afterglow lip balm orgasm: hydrogenated polyisobutene": "hydrogenated polyisobutene","afterglow lip shine:": "","aiko 475cm.:": "","airy:": "","alaria esculenta extract": "alaria esculenta extract","alba bark extract": "alba bark extract","alcium sodium borosilicate": "calcium sodium borosilicate","alcohol": "alcohol","alcohol  denat.": "alcohol","alcohol (organic)": "alcohol","alcohol denat": "alcohol","alcohol denat (sd alcohol 39-c)": "alcohol","alcohol denat.": "alcohol","alcohol denat. (sd alcohol 39-c .)": "alcohol","alcohol denat. (sd alcohol 39-c)": "alcohol","alcohol denat. (sd alcohol 39-c.)": "alcohol","alcohol denat. (sd alcohol 39c)": "alcohol","alcohol denat. 75% vol.": "alcohol","alcohol denat. parfum (fragrance)": "alcohol","alcohol denat./ sd alcohol 40-b": "alcohol","alcohol denat./sd alcohol 40-b": "alcohol","aleurites fordi oil copolymer": "aleurites fordi oil copolymer","aleurites moluccana seed oil": "aleurites moluccana seed oil","algae (seaweed) extract": "algae extract","algae extract": "algae extract","algae) extract": "algae extract","algal oil": "algal oil","alien goddess:": "","alien:": "","all - may contain (+/-) ci 16035 (red 40 lake)": "red 40 lake","all about clean 2-in-1 cleansing + exfoliating jelly:": "","all about clean liquid facial soap:": "","all about eyes eye cream:": "","all about shadow palette:": "","all diamond shades contain:": "","all original shades except dominique and krystal contain:": "","all other shades:": "","all shades (+/-) may contain/peut contenir: iron oxides (ci 77491": "iron oxides","all shades contain:": "","all shades:": "","all tint shades contain:": "","all voluspa candles are vegan and contain a clean-burning coconut wax blend": "","all-in-one nourishing eye cream:": "","all-in-one nourishing face cream:": "","all-in-one super nutrient face oil:": "","all-natural coconut and beeswax blend. paraffin-free. 100% braided cotton wick.": "","all-natural coconut-beeswax blend. paraffin-free. 100% braided cotton wick.": "","all-over wash for face": "","allantoin": "allantoin","allantoin: soothes the look of irritation and redness while supporting skin’s health.": "allantoin",": caprylic/capric triglyceride": "caprylic/capric triglyceride",": rayon": "rayon","a1": "","a1": "","a1:": "","a2": "","a2:": "","a3": "","a3": "","a3:": "","a4": "","a4:": "","a5": "","a5:": "","abeille royale advanced youth watery oil:": "","abeille royale anti-aging double r advanced serum:": "","abeille royale anti-aging fortifying lotion toner:": "","ablaze:": "","absolutely:": "","abundance:": "","acacia gum": "acacia Senegal gum","accepting:": "","aceite de moska:": "","acetate": "acetate","acetone": "acetone","acetyl cedrene": "acetyl cedrene","acid": "acid","acne clearing wash:": "","acne solutions cleansing foam:": "","acne solutions clinical clearing gel:": "","acne+ 2% bha acne spot treatment:": "","acne+ 2% bha cleanser:": "","acondicionador de cupuacu & castor:": "","acqua di gioia:": "","acqua neroli:": "","acrylate": "acrylate","acrylate copolymer.": "acrylate copolymer","acrylates/ethylhexl": "acrylates/ethylhexyl acrylate","acryloyldimethyl taurate copolymer": "acryloyldimethyl taurate copolymer","active blast concentrated collagen daily treatment:": "","active cartridge concentrate for pores & uneven texture:": "","active purple pore-refining antioxidant mask:": "","activist:": "","adaptogen activated mist:": "","adaptogen deep moisture cream:": "","adore me:": "","adriatic:": "","advanced clean dry shampoo:": "","advanced génifique eye cream:": "","advanced génifique face serum:": "","advanced génifique night cream:": "","advanced génifique yeux light pearl:": "","advanced génifique youth activating serum:": "","advanced night repair eye supercharged gel-creme synchronized multi-recovery:": "","advanced night repair synchronized multi-recovery complex:": "","adwoa blue tansy reparative mask water (aqua)": "water","aesthetic:": "","affair: mica": "mica","affinity 476sf:": "","affirmation:": "","affogato:": "","after dusk:": "","after hours:": "","afterglow lip balm in dolce vita:": "","afterglow lip balm in orgasm:": "","afterglow lip balm orgasm: hydrogenated polyisobutene": "hydrogenated polyisobutene","afterglow lip shine:": "","aiko 475cm.:": "","airy:": "","alaria esculenta extract": "alaria esculenta extract","alba bark extract": "alba bark extract","alcium sodium borosilicate": "calcium sodium borosilicate","alcohol": "alcohol","alcohol  denat.": "alcohol","alcohol (organic)": "alcohol","alcohol denat": "alcohol","alcohol denat (sd alcohol 39-c)": "alcohol","alcohol denat.": "alcohol","alcohol denat. (sd alcohol 39-c .)": "alcohol","alcohol denat. (sd alcohol 39-c)": "alcohol","alcohol denat. (sd alcohol 39-c.)": "alcohol","alcohol denat. (sd alcohol 39c)": "alcohol","alcohol denat. 75% vol.": "alcohol","alcohol denat. parfum (fragrance)": "alcohol","alcohol denat./ sd alcohol 40-b": "alcohol","alcohol denat./sd alcohol 40-b": "alcohol","aleurites fordi oil copolymer": "aleurites fordi oil copolymer","aleurites moluccana seed oil": "aleurites moluccana seed oil","algae (seaweed) extract": "algae extract","algae extract": "algae extract","algae) extract": "algae extract","algal oil": "algal oil","alien goddess:": "","alien:": "","all - may contain (+/-) ci 16035 (red 40 lake)": "red 40 lake","all about clean 2-in-1 cleansing + exfoliating jelly:": "","all about clean liquid facial soap:": "","all about eyes eye cream:": "","all about shadow palette:": "","all diamond shades contain:": "","all original shades except dominique and krystal contain:": "","all other shades:": "","all shades (+/-) may contain/peut contenir: iron oxides (ci 77491": "iron oxides","all shades contain:": "","all shades:": "","all tint shades contain:": "","all voluspa candles are vegan and contain a clean-burning coconut wax blend": "","all-in-one nourishing eye cream:": "","all-in-one nourishing face cream:": "","all-in-one super nutrient face oil:": "","all-natural coconut and beeswax blend. paraffin-free. 100% braided cotton wick.": "","all-natural coconut-beeswax blend. paraffin-free. 100% braided cotton wick.": "","all-over wash for face": "","allantoin": "allantoin","allantoin: soothes the look of irritation and redness while supporting skin’s health.": "allantoin",": caprylic/capric triglyceride": "caprylic/capric triglyceride",": rayon": "rayon","

##### Apply standardized replacements to ingredients

In [135]:
# Function to replace ingredients in each treatment list
def replace_ingredients(ingredient_str_list, replacements_dict):
    # print(ingredient_str_list)

    # Check if treatments is NULL or not a list (e.g., None)
    if ingredient_str_list is None or not isinstance(ingredient_str_list, list):
        return []

    # Check if treatments array is empty
    if len(ingredient_str_list) == 0:
        return []

    standardized_ingredients = []

    # Combine ingredients string into single list of ingredients
    ingredients = []
    for ingredient_str in ingredient_str_list:
      ingredients += ingredient_str.split(", ")

    # Iterate through each ingredient in the ingredients array
    ingredients = [x.lower().replace("\"", "").strip() for x in ingredients]
    for ingredient in ingredients:
        # Replace with standardized name if it exists in the replacements dictionary
        # if (ingredient in replacements_dict):
        #   print("REPLACED: ", ingredient, "WITH", replacements_dict[ingredient])
        standardized_ingredient = replacements_dict.get(ingredient, ingredient)
        standardized_ingredient = standardized_ingredient.replace("\"", "").strip()

        if (standardized_ingredient != ""):
          standardized_ingredients.append(standardized_ingredient)

    # print(ingredients)
    # print(standardized_ingredients)
    # print()

    return standardized_ingredients

# Function to safely apply literal_eval only when needed
def ensure_list(val):
    # If the value is a NumPy array, convert it to a list
    if isinstance(val, np.ndarray):
        # print("original nparray val: ", val)
        val_as_list = val.tolist()
        # print("list val: ", val_as_list)

        # If tolist() returns a string or other non-list type, wrap it in a list
        if isinstance(val_as_list, str):
            # print("wrapped val: ", [val_as_list])
            return [val_as_list]

        return val_as_list

# Fetch the data from BigQuery into a DataFrame
sephora_product_sql = "select * from skincare_products_stg.sephora_product"
product_rows = pandas_gbq.read_gbq(sephora_product_sql, project_id=project_id)

# Convert lists to JSON strings for BigQuery compatibility
product_rows["ingredients"] = product_rows["ingredients"].apply(ensure_list)
product_rows["ingredients"] = product_rows["ingredients"].apply(lambda x: replace_ingredients(x, replacements))
product_rows["ingredients"] = product_rows["ingredients"].apply(lambda x: json.dumps(x) if isinstance(x, list) else x)

# # Apply the replacement to each row's treatments list
print("new df:", product_rows)

# # Upload the updated DataFrame back to BigQuery
table_id = f"{project_id}.skincare_products_stg.sephora_product"
pandas_gbq.to_gbq(product_rows, table_id, project_id=project_id, if_exists='replace')

Downloading: 100%|██████████|
new df:      product_id                                      product_name brand_id  \
0       P474053                                Glossy Nail Polish     1063
1       P478711                                 Nail Art Stickers     1063
2       P432502                       BACKSTAGE Glow Face Palette     1073
3       P457666  J'adore Eau Lumière Eau de Toilette Roller-pearl     1073
4       P379408                                         Nail Glow     1073
...         ...                                               ...      ...
8489    P434223        The Brush Crush Heated Straightening Brush     7004
8490    P449576      The Tress Press Straightening Iron 1.25 Inch     7004
8491    P406232                           10X Pro Styling Iron 1"     7086
8492    P460864                           OnePass 1" Styling Iron     7086
8493    P442581                        GrapheneMX Styling Iron 1"     7086

     brand_name  loves_count  rating  reviews other_size imperial_size  \
0         Gucci        36591  3.5806       62       None      0.33 oz
1         Gucci         4551  1.9355       31       None          None
2          Dior       229844  4.5317      961       None          None
3          Dior         7763  4.1000       10       None       0.67 oz
4          Dior        39646  4.1767      566       None       0.33 oz
...         ...          ...     ...      ...        ...           ...
8489     Drybar        17529  4.2593      270       None          None
8490     Drybar         2258  2.7857       14       None          None
8491  Bio Ionic        14851  4.2816      206       None          None
8492  Bio Ionic          840  2.7500        8       None          None
8493  Bio Ionic         1213  3.2500        8       None          None

     metric_size  ... new_product  online_only  out_of_stock  \
0           10 g  ...        True         True         False
1           None  ...       False         True         False
2           None  ...       False        False         False
3          20 mL  ...       False        False         False
4          10 mL  ...       False        False         False
...          ...  ...         ...          ...           ...
8489        None  ...       False        False         False
8490        None  ...       False        False         False
8491        None  ...       False        False         False
8492        None  ...       False         True         False
8493        None  ...       False        False         False

      sephora_exclusive                                 feature_highlights  \
0                 False  ['Vegan', 'High Shine Finish', 'Full Coverage'...
1                 False                                               None
2                  True                                               None
3                 False                                               None
4                 False                                               None
...                 ...                                                ...
8489              False  ['All Hair Types', 'Good for: Frizz', 'Increas...
8490              False                                               None
8491              False  ['All Hair Types', 'Increases Shine', 'Good fo...
8492              False  ['All Hair Types', 'Increases Shine', 'Good fo...
8493              False  ['All Hair Types', 'Increases Shine', 'Good fo...

      primary_category  secondary_category                tertiary_category  \
0               Makeup                Nail                             None
1               Makeup                Nail                             None
2               Makeup     Makeup Palettes                             None
3            Mini Size           Fragrance                             None
4               Makeup                Nail                             None
...                ...                 ...                              ...
8489              Hair               Tools  Hair Straighteners & Flat Irons
8490              Hair               Tools  Hair Straighteners & Flat Irons
8491              Hair               Tools  Hair Straighteners & Flat Irons
8492              Hair               Tools  Hair Straighteners & Flat Irons
8493              Hair               Tools  Hair Straighteners & Flat Irons

         _data_source                       _load_time
0     sephora_product 2024-09-25 02:15:33.136361+00:00
1     sephora_product 2024-09-25 02:15:33.136361+00:00
2     sephora_product 2024-09-25 02:15:33.136361+00:00
3     sephora_product 2024-09-25 02:15:33.136361+00:00
4     sephora_product 2024-09-25 02:15:33.136361+00:00
...               ...                              ...
8489  sephora_product 2024-09-25 02:15:33.136361+00:00
8490  sephora_product 2024-09-25 02:15:33.136361+00:00
8491  sephora_product 2024-09-25 02:15:33.136361+00:00
8492  sephora_product 2024-09-25 02:15:33.136361+00:00
8493  sephora_product 2024-09-25 02:15:33.136361+00:00

[8494 rows x 29 columns]

100%|██████████| 1/1 [00:00<00:00, 6114.15it/s]

##### Cast ingredients column to array

In [136]:
%%bigquery
SELECT
  -- Use JSON_EXTRACT_ARRAY to convert the cleaned string into an array
  JSON_EXTRACT_ARRAY(ingredients) AS ingredients
FROM
  `skincare_products_stg.sephora_product`

Query is running:   0%|          |

Downloading:   0%|          |

                                            ingredients
0     ["alcohol", "fragrance", "dipropylene glycol",...
1     ["alcohol denat.", "water", "fragrance", "ethy...
2     ["aqua (water)", "butylene glycol", "glycerin"...
3     ["alcohol", "parfum/fragrance", "aqua/water", ...
4     ["silica", "mica", "dimethicone/divinyldimethi...
...                                                 ...
8489                                                 []
8490                                                 []
8491                                                 []
8492                                                 []
8493                                                 []

[8494 rows x 1 columns]

In [137]:
%%bigquery
create or replace table skincare_products_stg.sephora_product as
  select
    product_id,
    product_name,
    brand_id,
    brand_name,
    loves_count,
    rating,
    reviews,
    other_size,
    imperial_size,
    metric_size,
    color,
    variation_count,
    variation_max_price,
    variation_min_price,
    JSON_EXTRACT_ARRAY(ingredients) as ingredients,
    price_usd,
    value_price_usd,
    sale_price_usd,
    limited_edition,
    new_product,
    online_only,
    out_of_stock,
    sephora_exclusive,
    feature_highlights,
    primary_category,
    secondary_category,
    tertiary_category,
    _data_source,
    _load_time
  from skincare_products_stg.sephora_product

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

##### Verify ingredients have been standardized

In [138]:
%%bigquery
WITH flattened_ingredients AS (
  -- Flatten the array into individual rows
  SELECT
    LOWER(TRIM(ingredient)) AS ingredient -- Convert to lowercase and trim spaces to handle case/whitespace variations
  FROM
    skincare_products_stg.sephora_product,
    UNNEST(ingredients) AS ingredient -- Unnest the arrays into individual strings
  WHERE
    ingredients IS NOT NULL
)
-- Select distinct treatments and sort them alphabetically
SELECT DISTINCT ingredient
FROM flattened_ingredients
ORDER BY ingredient;

Query is running:   0%|          |

Downloading:   0%|          |

                                          ingredient
0                                 "#12103/a alcohol"
1                                    "#14881/a talc"
2                                          "#17515:"
3                                          "#17541:"
4                                          "#17627:"
...                                              ...
18380  "¬glycyrrhiza glabra (licorice) root extract"
18381        "˝adore: calcium aluminum borosilicate"
18382                               "α-phellandrene"
18383                          "ψ hydrolyzed quinoa"
18384                 "‎acorus calamus (sweet flag)"

[18385 rows x 1 columns]

### `sephora_product_review` table

#### Cast `author_id` from STRING to INTEGER

In [86]:
%%bigquery
select author_id as orig_author_id, safe_cast(author_id as INTEGER) as new_author_id
from skincare_products_raw.sephora_product_review
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

  orig_author_id  new_author_id
0     2652440379     2652440379
1     5123288012     5123288012
2     8577823224     8577823224
3     1812815731     1812815731
4     9348546709     9348546709

#### Cast `is_recommended` from FLOAT to BOOL

In [87]:
%%bigquery
select
  is_recommended as orig_is_recommended,
  CASE
    WHEN is_recommended = 1 THEN TRUE
    WHEN is_recommended = 0 THEN FALSE
    ELSE NULL
  END as new_is_recommended
from skincare_products_raw.sephora_product_review
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

   orig_is_recommended  new_is_recommended
0                  NaN                <NA>
1                  NaN                <NA>
2                  NaN                <NA>
3                  1.0                True
4                  1.0                True

#### Replace values of `Grey` with `Gray` in `eye_color` field

In [88]:
%%bigquery
select
  eye_color as orig_eye_color,
  case eye_color when 'Grey' then 'gray' else eye_color end as new_eye_color
from skincare_products_raw.sephora_product_review
limit 100

Query is running:   0%|          |

Downloading:   0%|          |

   orig_eye_color new_eye_color
0            None          None
1            None          None
2            None          None
3           brown         brown
4           brown         brown
..            ...           ...
95           None          None
96          brown         brown
97           None          None
98           None          None
99          brown         brown

[100 rows x 2 columns]

#### Rename `total_feedback_*` fields to something that makes more sense

In [89]:
%%bigquery
select
  total_feedback_count as review_feedback_count,
  total_pos_feedback_count as review_upvote_count,
  total_neg_feedback_count as review_downvote_count,
from skincare_products_raw.sephora_product_review
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

   review_feedback_count  review_upvote_count  review_downvote_count
0                     39                   12                     27
1                      7                    3                      4
2                     19                   18                      1
3                     12                    1                     11
4                     68                   60                      8

#### Drop `row_number` field

In [ ]:
# Leave out row_number during `select` query

#### Putting it all together

In [90]:
%%bigquery
select
  safe_cast(author_id as INTEGER) as author_id,
  rating,
  CASE
    WHEN is_recommended = 1 THEN TRUE
    WHEN is_recommended = 0 THEN FALSE
    ELSE NULL
  END as is_recommended,
  helpfulness,
  total_feedback_count as review_feedback_count,
  total_pos_feedback_count as review_upvote_count,
  total_neg_feedback_count as review_downvote_count,
  submission_time,
  review_text,
  review_title,
  skin_tone,
  case eye_color when 'Grey' then 'gray' else eye_color end as new_eye_color,
  skin_type,
  hair_color,
  product_id,
  product_name,
  brand_name,
  price_usd,
  _data_source,
  _load_time,
from skincare_products_raw.sephora_product_review

Query is running:   0%|          |

Downloading:   0%|          |

,author_id,rating,is_recommended,helpfulness,review_feedback_count,review_upvote_count,review_downvote_count,submission_time,review_text,review_title,skin_tone,new_eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd,_data_source,_load_time
0,1533231934,4,<NA>,0.250000,4,1,3,2008-10-25,Murad’s exfoliating cleanser is a good product...,Very good cleanser...,fair,None,oily,None,P4010,AHA/BHA Exfoliating Cleanser,Murad,46.0,sephora_product_review,2024-09-25 02:15:00.273556+00:00
1,9548845160,5,<NA>,0.930233,43,40,3,2017-03-27,I struggled with acne on my forehead and templ...,MY MOST RECOMMENDED PRODUCT,None,None,oily,None,P4016,Acne Control Clarifying Cleanser,Murad,36.0,sephora_product_review,2024-09-25 02:15:00.273556+00:00
2,25285368579,2,False,0.777778,9,7,2,2021-02-12,"I bought the travel size, tried it for like tw...",Dried out my oily skin,lightMedium,brown,oily,brown,P4016,Acne Control Clarifying Cleanser,Murad,36.0,sephora_product_review,2024-09-25 02:15:00.273556+00:00
3,2177603932,1,<NA>,0.200000,5,1,4,2015-03-24,it makes my skins so dry and .. i don’t like t...,do not like the smell,None,None,None,None,P12045,Grape Water Moisturizing Face Mist,Caudalie,12.0,sephora_product_review,2024-09-25 02:15:00.273556+00:00
4,1450844384,1,<NA>,0.272727,11,3,8,2009-10-30,not verey good producet to oily even for dry skin,fresh sugar face polish 4.2 oz,lightMedium,None,dry,None,P12295,Sugar Face Polish Exfoliator,fresh,64.0,sephora_product_review,2024-09-25 02:15:00.273556+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1094406,30165722656,3,False,0.333333,6,2,4,2021-09-06,"After reading about the one day results, I gav...",None,fairLight,blue,dry,brown,P503191,Mini Indigo Overnight Repair Serum in Cream Tr...,Tatcha,22.0,sephora_product_review,2024-09-25 02:15:00.273556+00:00
1094407,40261604063,5,True,0.333333,3,1,2,2022-12-20,I have red spots on my face and just within a ...,A new staple in my routine,fair,hazel,combination,None,P503693,Bouncy Brightfacial Brightening Mask with 10% ...,Drunk Elephant,68.0,sephora_product_review,2024-09-25 02:15:00.273556+00:00
1094408,6908668210,5,True,0.333333,3,1,2,2020-08-12,I received this product complementary for test...,I love it!! Perfect cleanser!,light,brown,normal,black,P504595,Mini Rice Wash Skin-Softening Cleanser,Tatcha,18.0,sephora_product_review,2024-09-25 02:15:00.273556+00:00
1094409,5045348881,3,False,0.333333,6,2,4,2020-08-16,I tried this cleanser a couple of times and I ...,Gross Smell,lightMedium,brown,combination,brown,P504615,Mini Deep Cleanse Gentle Exfoliating Cleanser,Tatcha,18.0,sephora_product_review,2024-09-25 02:15:00.273556+00:00
1094410,20932008877,4,True,0.333333,3,1,2,2023-03-09,This was gifted to me by Skinfix in exchange f...,None,tan,brown,combination,black,P505049,barrier+ Triple Lipid + Collagen Brightening E...,Skinfix,54.0,sephora_product_review,2024-09-25 02:15:00.273556+00:00

#### Create Staging table

In [91]:
%%bigquery
create or replace table skincare_products_stg.sephora_product_review as
  select
    safe_cast(author_id as INTEGER) as author_id,
    rating,
    CASE
      WHEN is_recommended = 1 THEN TRUE
      WHEN is_recommended = 0 THEN FALSE
      ELSE NULL
    END as is_recommended,
    helpfulness,
    total_feedback_count as review_feedback_count,
    total_pos_feedback_count as review_upvote_count,
    total_neg_feedback_count as review_downvote_count,
    submission_time,
    review_text,
    review_title,
    skin_tone,
    case eye_color when 'Grey' then 'gray' else eye_color end as new_eye_color,
    skin_type,
    hair_color,
    product_id,
    product_name,
    brand_name,
    price_usd,
    _data_source,
    _load_time,
  from skincare_products_raw.sephora_product_review

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

### `skin_disease_picture` table

##### Replace `'N/A'` with null

In [92]:
%%bigquery
select
case skin_condition_name when 'N/A' then null else skin_condition_name end as skin_condition_name,
case skin_color when 'N/A' then null else skin_color end as skin_color,
case severity when 'N/A' then null else severity end as severity,
case image_link when 'N/A' then null else image_link end as image_link,
  _data_source, _load_time
  from skincare_products_raw.skin_disease_picture;

Query is running:   0%|          |

Downloading:   0%|          |

,skin_condition_name,skin_color,severity,image_link,_data_source,_load_time
0,aids,red,severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
1,ctcl,red,severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
2,ctcl,red,severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
3,ctcl,red,moderate,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
4,ctcl,red,moderate,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
...,...,...,...,...,...,...
3813,vitiligo,"light brown, white",moderate,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
3814,pseudomonas_cellulitis,"red, green, yellow",severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
3815,vasculitis,"red, purple, brown",severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
3816,pyoderma_gangrenosum,"red, yellow, and purple",severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
3817,vasculitis,"red, purple, brown, and black",severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00

##### Look for empty strings

In [93]:
%%bigquery
select count(*) as empty_skin_condition_name
from skincare_products_raw.skin_disease_picture
where skin_condition_name = '';

Query is running:   0%|          |

Downloading:   0%|          |

   empty_skin_condition_name
0                          0

In [94]:
%%bigquery
select count(*) as empty_skin_color
from skincare_products_raw.skin_disease_picture
where skin_color = '';

Query is running:   0%|          |

Downloading:   0%|          |

   empty_skin_color
0                 0

In [95]:
%%bigquery
select count(*) as empty_severity
from skincare_products_raw.skin_disease_picture
where severity = '';

Query is running:   0%|          |

Downloading:   0%|          |

   empty_severity
0               0

In [96]:
%%bigquery
select count(*) as empty_image_link
from skincare_products_raw.skin_disease_picture
where image_link = '';

Query is running:   0%|          |

Downloading:   0%|          |

   empty_image_link
0                 0

##### Putting it all together

In [97]:
%%bigquery
select
case skin_condition_name
  when 'N/A' then null
  when '\\N' then null
  when '' then null
  else skin_condition_name
  end as skin_condition_name,
case skin_color
  when 'N/A' then null
  when '\\N' then null
  when '' then null
  else skin_color
  end as affected_skin_color,
case severity
  when 'N/A' then null
  when '\\N' then null
  when '' then null
  else severity
  end as severity,
case image_link
  when 'N/A' then null
  when '\\N' then null
  when '' then null
  else image_link
  end as image_link,
_data_source, _load_time
from skincare_products_raw.skin_disease_picture;

Query is running:   0%|          |

Downloading:   0%|          |

,skin_condition_name,affected_skin_color,severity,image_link,_data_source,_load_time
0,aids,red,severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
1,ctcl,red,severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
2,ctcl,red,severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
3,ctcl,red,moderate,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
4,ctcl,red,moderate,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
...,...,...,...,...,...,...
3813,vitiligo,"light brown, white",moderate,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
3814,pseudomonas_cellulitis,"red, green, yellow",severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
3815,vasculitis,"red, purple, brown",severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
3816,pyoderma_gangrenosum,"red, yellow, and purple",severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00
3817,vasculitis,"red, purple, brown, and black",severe,https://storage.cloud.google.com/skincare-prod...,skin_disease_picture,2024-09-25 02:15:36.624486+00:00

##### Create staging table

In [98]:
%%bigquery
create or replace table skincare_products_stg.skin_disease_picture as
  select
case skin_condition_name
  when 'N/A' then null
  when '\\N' then null
  when '' then null
  else skin_condition_name
  end as skin_condition_name,
case skin_color
  when 'N/A' then null
  when '\\N' then null
  when '' then null
  else skin_color
  end as affected_skin_color,
case severity
  when 'N/A' then null
  when '\\N' then null
  when '' then null
  else severity
  end as severity,
case image_link
  when 'N/A' then null
  when '\\N' then null
  when '' then null
  else image_link
  end as image_link,
_data_source, _load_time
from skincare_products_raw.skin_disease_picture;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

#### Standardize the skin_color field with LLM

In [99]:
%%bigquery
select skin_condition_name
from skincare_products_raw.skin_disease_picture
group by skin_condition_name
order by skin_condition_name

Query is running:   0%|          |

Downloading:   0%|          |

                 skin_condition_name
0                           11img017
1                           11img018
2                           11img019
3                           14img010
4                            1img011
..                               ...
515               weathering_nodules
516  white_superficial_onychomycosis
517              x_linked_ichthyosis
518                        xanthomas
519                     yellow_nails

[520 rows x 1 columns]

##### Test skin_color standardization

In [ ]:
import json
import vertexai
from vertexai.generative_models import GenerativeModel
from google.cloud import bigquery

project_id = "segfault-434120"
region = "us-central1"
model_name = "gemini-1.5-flash-001"

prompt = """
Go through this list of affected_skin_color values and look for values that have similar meanings but were given different names.
For example, 'light brown' and 'brownish' could be standardized to 'brown'.
Suggest a standard value, mapping the current one to the new one.
Return the list of original values along with their new values.
Format the results as a json object with the schema: current_value:string, new_value:string.
Do not include any unchanged values in your answer.
Do not include an explanation with your answer.
"""

skin_color_sql = """select distinct affected_skin_color
                    from skincare_products_raw.skin_disease_picture
                    where affected_skin_color is not null
                    order by affected_skin_color"""

skin_disease_pictures_sql = """select *
                               from skincare_products_raw.skin_disease_picture
                               where affected_skin_color is not null"""

bq_client = bigquery.Client()

rows = bq_client.query(skin_color_sql).result()

skin_color_list = [row["affected_skin_color"] for row in rows]
skin_color_str = '\n'.join(skin_color_list)

print("skin_color_str:", skin_color_str)

vertexai.init(project=project_id, location=region)
model = GenerativeModel(model_name)

resp = model.generate_content([skin_color_str, prompt])
resp_text = resp.text.replace("```json", "").replace("```", "").replace("\n", "")

print(resp_text)
skin_color_mappings = json.loads(resp_text)
print("skin_color_mappings:", skin_color_mappings)

replacements = {}
for old, new in skin_color_mappings.items():
    if old != new:
        replacements[old] = new

print("replacements:", replacements)

df = bq_client.query(skin_disease_pictures_sql).to_dataframe()

print("Original df:", df)

df["affected_skin_color"] = df["affected_skin_color"].map(replacements).fillna(df["affected_skin_color"])

print("Updated df:", df)

skin_color_str: black
blue
brown
brown and white
brownish
brownish-purple
dark
dark brown
fair
gray
green
grey
light
light brown
light brown, white
light green
light pink
light skin
light tan
light-brown
light-pink
light-skinned
light_brown
light_pink
light_red
light_skin
light_skin_tone
medium brown
null
orange
pale
pale pink
pale yellow
pale_yellow
pigmented
pink
pink, red
pinkish
pinkish red
pinkish-red
pinkish-white
pinkish_red
purple
red
red and purple
red, brown
red, brown, black
red, brown, white
red, green, yellow
red, purple, brown
red, purple, brown, and black
red, white
red, yellow
red, yellow, and purple
red_and_purple
reddish
reddish-brown
skin tone
tan
unknown
white
white, brown
white, red
yellow
yellowish
yellowish, red
yellowish_green
{"brownish": "brown","brownish-purple": "brown","dark brown": "brown","fair": "light","grey": "gray","light brown": "brown","light brown, white": "brown","light green": "green","light pink": "pink","light skin": "light","light tan": "light","light-brown": "brown","light-pink": "pink","light-skinned": "light","light_brown": "brown","light_pink": "pink","light_red": "red","light_skin": "light","light_skin_tone": "light","medium brown": "brown","pale pink": "pink","pale yellow": "yellow","pale_yellow": "yellow","pink, red": "pink","pinkish": "pink","pinkish red": "pink","pinkish-red": "pink","pinkish-white": "pink","pinkish_red": "pink","red and purple": "purple","red, brown": "brown","red, brown, black": "brown","red, brown, white": "brown","red, green, yellow": "red","red, purple, brown": "brown","red, purple, brown, and black": "brown","red, white": "red","red, yellow": "red","red, yellow, and purple": "red","red_and_purple": "purple","reddish": "red","reddish-brown": "brown","skin tone": "null","white, brown": "brown","white, red": "red","yellowish": "yellow","yellowish, red": "yellow","yellowish_green": "green"}
skin_color_mappings: {'brownish': 'brown', 'brownish-purple': 'brown', 'dark brown': 'brown', 'fair': 'light', 'grey': 'gray', 'light brown': 'brown', 'light brown, white': 'brown', 'light green': 'green', 'light pink': 'pink', 'light skin': 'light', 'light tan': 'light', 'light-brown': 'brown', 'light-pink': 'pink', 'light-skinned': 'light', 'light_brown': 'brown', 'light_pink': 'pink', 'light_red': 'red', 'light_skin': 'light', 'light_skin_tone': 'light', 'medium brown': 'brown', 'pale pink': 'pink', 'pale yellow': 'yellow', 'pale_yellow': 'yellow', 'pink, red': 'pink', 'pinkish': 'pink', 'pinkish red': 'pink', 'pinkish-red': 'pink', 'pinkish-white': 'pink', 'pinkish_red': 'pink', 'red and purple': 'purple', 'red, brown': 'brown', 'red, brown, black': 'brown', 'red, brown, white': 'brown', 'red, green, yellow': 'red', 'red, purple, brown': 'brown', 'red, purple, brown, and black': 'brown', 'red, white': 'red', 'red, yellow': 'red', 'red, yellow, and purple': 'red', 'red_and_purple': 'purple', 'reddish': 'red', 'reddish-brown': 'brown', 'skin tone': 'null', 'white, brown': 'brown', 'white, red': 'red', 'yellowish': 'yellow', 'yellowish, red': 'yellow', 'yellowish_green': 'green'}
replacements: {'brownish': 'brown', 'brownish-purple': 'brown', 'dark brown': 'brown', 'fair': 'light', 'grey': 'gray', 'light brown': 'brown', 'light brown, white': 'brown', 'light green': 'green', 'light pink': 'pink', 'light skin': 'light', 'light tan': 'light', 'light-brown': 'brown', 'light-pink': 'pink', 'light-skinned': 'light', 'light_brown': 'brown', 'light_pink': 'pink', 'light_red': 'red', 'light_skin': 'light', 'light_skin_tone': 'light', 'medium brown': 'brown', 'pale pink': 'pink', 'pale yellow': 'yellow', 'pale_yellow': 'yellow', 'pink, red': 'pink', 'pinkish': 'pink', 'pinkish red': 'pink', 'pinkish-red': 'pink', 'pinkish-white': 'pink', 'pinkish_red': 'pink', 'red and purple': 'purple', 'red, brown': 'brown', 'red, brown, black': 'brown', 'red, brown, white': 'brown', 'red, green, yellow': 'red', 'red, purple, brown': 'brown', 'red, purple, brown, and black': 'brown', 'red, white': 'red', 'red, yellow': 'red', 'red, yellow, and purple': 'red', 'red_and_purple': 'purple', 'reddish': 'red', 'reddish-brown': 'brown', 'skin tone': 'null', 'white, brown': 'brown', 'white, red': 'red', 'yellowish': 'yellow', 'yellowish, red': 'yellow', 'yellowish_green': 'green'}
Original df:          skin_condition_name                     skin_color  severity  \
0                       aids                            red    severe
1                       ctcl                            red    severe
2                       ctcl                            red    severe
3                       ctcl                            red  moderate
4                       ctcl                            red  moderate
...                      ...                            ...       ...
3813                vitiligo             light brown, white  moderate
3814  pseudomonas_cellulitis             red, green, yellow    severe
3815              vasculitis             red, purple, brown    severe
3816    pyoderma_gangrenosum        red, yellow, and purple    severe
3817              vasculitis  red, purple, brown, and black    severe

                                             image_link          _data_source  \
0     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
1     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
2     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
4     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
...                                                 ...                   ...
3813  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3814  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3815  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3816  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3817  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture

                           _load_time
0    2024-09-25 02:15:36.624486+00:00
1    2024-09-25 02:15:36.624486+00:00
2    2024-09-25 02:15:36.624486+00:00
3    2024-09-25 02:15:36.624486+00:00
4    2024-09-25 02:15:36.624486+00:00
...                               ...
3813 2024-09-25 02:15:36.624486+00:00
3814 2024-09-25 02:15:36.624486+00:00
3815 2024-09-25 02:15:36.624486+00:00
3816 2024-09-25 02:15:36.624486+00:00
3817 2024-09-25 02:15:36.624486+00:00

[3818 rows x 6 columns]
Updated df:          skin_condition_name skin_color  severity  \
0                       aids        red    severe
1                       ctcl        red    severe
2                       ctcl        red    severe
3                       ctcl        red  moderate
4                       ctcl        red  moderate
...                      ...        ...       ...
3813                vitiligo      brown  moderate
3814  pseudomonas_cellulitis        red    severe
3815              vasculitis      brown    severe
3816    pyoderma_gangrenosum        red    severe
3817              vasculitis      brown    severe

                                             image_link          _data_source  \
0     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
1     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
2     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
4     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
...                                                 ...                   ...
3813  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3814  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3815  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3816  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3817  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture

                           _load_time
0    2024-09-25 02:15:36.624486+00:00
1    2024-09-25 02:15:36.624486+00:00
2    2024-09-25 02:15:36.624486+00:00
3    2024-09-25 02:15:36.624486+00:00
4    2024-09-25 02:15:36.624486+00:00
...                               ...
3813 2024-09-25 02:15:36.624486+00:00
3814 2024-09-25 02:15:36.624486+00:00
3815 2024-09-25 02:15:36.624486+00:00
3816 2024-09-25 02:15:36.624486+00:00
3817 2024-09-25 02:15:36.624486+00:00

[3818 rows x 6 columns]

##### Apply affected_skin_color standardization to staging table

In [101]:
import json
import pandas_gbq
import vertexai
from vertexai.generative_models import GenerativeModel, Part
from google.cloud import bigquery

project_id = "segfault-434120"
region = "us-central1"
model_name = "gemini-1.5-flash-001"
prompt = """
Go through this list of affected_skin_color values and look for values that have similar meanings but were given different names.
For example, 'rosacea', 'acne rosacea', and 'rosacea (acne)' could all be standardized to 'rosacea'.
Suggest a standard value, mapping the current one to the new one.
Return the list of original values along with their new values.
Format the results as a json object with the schema: current_value:string, new_value:string.
Do not include any unchanged values in your answer.
Do not include an explanation with your answer.
"""
skin_color_sql = """select distinct affected_skin_color
                    from skincare_products_stg.skin_disease_picture
                    where affected_skin_color is not null
                    order by affected_skin_color"""

skin_disease_picture_sql = """select *
                               from skincare_products_stg.skin_disease_picture
                               where affected_skin_color is not null"""

bq_client = bigquery.Client()
rows = bq_client.query_and_wait(skin_color_sql)

category_list = []
for row in rows:
    category_list.append(row["affected_skin_color"])
category_str = '\n'.join(category_list)

vertexai.init(project=project_id, location=region)
model = GenerativeModel(model_name)
resp = model.generate_content([category_str, prompt])
resp_text = resp.text.replace("```json", "").replace("```", "").replace("\n", "")
print(resp_text)
categories = json.loads(resp_text)
print(type(categories))

replacements = {} # will store the new categories

# categories can be either a dictionary or list type (depending on what LLM decides to do!)
if type(categories) == dict:
    for old, new in categories.items():
        if old == new:
            continue
        else:
            replacements[old] = new

if type(categories) == list:
    for cat_entry in categories:
        if cat_entry['current_category'] == cat_entry['new_category']:
            continue
        else:
            replacements[cat_entry['current_category']] = cat_entry['new_category']

print("replacements:", replacements)

df = bq_client.query_and_wait(skin_disease_picture_sql).to_dataframe()
print("orig df:", df)

df["affected_skin_color"] = df["affected_skin_color"].map(replacements).fillna(df["affected_skin_color"])
print("new df:", df)

table_id = "skincare_products_stg.skin_disease_picture"
pandas_gbq.to_gbq(df, table_id, project_id=project_id, if_exists="replace")

{"brownish": "brown","brownish-purple": "brown","dark brown": "brown","fair": "light","grey": "gray","light brown": "brown","light brown, white": "brown","light green": "green","light pink": "pink","light skin": "light","light tan": "tan","light-brown": "brown","light-pink": "pink","light-skinned": "light","light_brown": "brown","light_pink": "pink","light_red": "red","light_skin": "light","light_skin_tone": "light","medium brown": "brown","pale pink": "pink","pale yellow": "yellow","pale_yellow": "yellow","pink, red": "pink","pinkish": "pink","pinkish red": "pink","pinkish-red": "pink","pinkish-white": "pink","pinkish_red": "pink","red and purple": "red","red, brown": "red","red, brown, black": "red","red, brown, white": "red","red, green, yellow": "red","red, purple, brown": "red","red, purple, brown, and black": "red","red, white": "red","red, yellow": "red","red, yellow, and purple": "red","red_and_purple": "red","reddish": "red","reddish-brown": "red","skin tone": "tan","white, brown": "brown","white, red": "red","yellowish": "yellow","yellowish, red": "yellow","yellowish_green": "yellow"}
<class 'dict'>
replacements: {'brownish': 'brown', 'brownish-purple': 'brown', 'dark brown': 'brown', 'fair': 'light', 'grey': 'gray', 'light brown': 'brown', 'light brown, white': 'brown', 'light green': 'green', 'light pink': 'pink', 'light skin': 'light', 'light tan': 'tan', 'light-brown': 'brown', 'light-pink': 'pink', 'light-skinned': 'light', 'light_brown': 'brown', 'light_pink': 'pink', 'light_red': 'red', 'light_skin': 'light', 'light_skin_tone': 'light', 'medium brown': 'brown', 'pale pink': 'pink', 'pale yellow': 'yellow', 'pale_yellow': 'yellow', 'pink, red': 'pink', 'pinkish': 'pink', 'pinkish red': 'pink', 'pinkish-red': 'pink', 'pinkish-white': 'pink', 'pinkish_red': 'pink', 'red and purple': 'red', 'red, brown': 'red', 'red, brown, black': 'red', 'red, brown, white': 'red', 'red, green, yellow': 'red', 'red, purple, brown': 'red', 'red, purple, brown, and black': 'red', 'red, white': 'red', 'red, yellow': 'red', 'red, yellow, and purple': 'red', 'red_and_purple': 'red', 'reddish': 'red', 'reddish-brown': 'red', 'skin tone': 'tan', 'white, brown': 'brown', 'white, red': 'red', 'yellowish': 'yellow', 'yellowish, red': 'yellow', 'yellowish_green': 'yellow'}
orig df:          skin_condition_name            affected_skin_color  severity  \
0         hemangioma_infancy                            red      mild
1         pyogenic_granuloma                            red      mild
2       chilblains_perniosis                            red      mild
3       erythema_infectiosum                            red      mild
4         bullous_pemphigoid                            red      mild
...                      ...                            ...       ...
3813                vitiligo             light brown, white  moderate
3814  pseudomonas_cellulitis             red, green, yellow    severe
3815              vasculitis             red, purple, brown    severe
3816    pyoderma_gangrenosum        red, yellow, and purple    severe
3817              vasculitis  red, purple, brown, and black    severe

                                             image_link          _data_source  \
0     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
1     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
2     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
4     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
...                                                 ...                   ...
3813  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3814  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3815  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3816  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3817  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture

                           _load_time
0    2024-09-25 02:15:36.624486+00:00
1    2024-09-25 02:15:36.624486+00:00
2    2024-09-25 02:15:36.624486+00:00
3    2024-09-25 02:15:36.624486+00:00
4    2024-09-25 02:15:36.624486+00:00
...                               ...
3813 2024-09-25 02:15:36.624486+00:00
3814 2024-09-25 02:15:36.624486+00:00
3815 2024-09-25 02:15:36.624486+00:00
3816 2024-09-25 02:15:36.624486+00:00
3817 2024-09-25 02:15:36.624486+00:00

[3818 rows x 6 columns]
new df:          skin_condition_name affected_skin_color  severity  \
0         hemangioma_infancy                 red      mild
1         pyogenic_granuloma                 red      mild
2       chilblains_perniosis                 red      mild
3       erythema_infectiosum                 red      mild
4         bullous_pemphigoid                 red      mild
...                      ...                 ...       ...
3813                vitiligo               brown  moderate
3814  pseudomonas_cellulitis                 red    severe
3815              vasculitis                 red    severe
3816    pyoderma_gangrenosum                 red    severe
3817              vasculitis                 red    severe

                                             image_link          _data_source  \
0     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
1     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
2     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
4     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
...                                                 ...                   ...
3813  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3814  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3815  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3816  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3817  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture

                           _load_time
0    2024-09-25 02:15:36.624486+00:00
1    2024-09-25 02:15:36.624486+00:00
2    2024-09-25 02:15:36.624486+00:00
3    2024-09-25 02:15:36.624486+00:00
4    2024-09-25 02:15:36.624486+00:00
...                               ...
3813 2024-09-25 02:15:36.624486+00:00
3814 2024-09-25 02:15:36.624486+00:00
3815 2024-09-25 02:15:36.624486+00:00
3816 2024-09-25 02:15:36.624486+00:00
3817 2024-09-25 02:15:36.624486+00:00

[3818 rows x 6 columns]

100%|██████████| 1/1 [00:00<00:00, 9686.61it/s]

#### Standardize the skin_condition_name field with LLM

##### Test skin_condition_name standardization

In [ ]:
import json
import vertexai
from vertexai.generative_models import GenerativeModel
from google.cloud import bigquery

project_id = "segfault-434120"
region = "us-central1"
model_name = "gemini-1.5-flash-001"

prompt = """
Go through this list of skin_condition_name values and look for values that have similar meanings but were given different names.
For example, 'rosacea', 'acne rosacea', and 'rosacea (acne)' could all be standardized to 'rosacea'.
Suggest a standard value, mapping the current one to the new one.
Return the list of original values along with their new values.
Format the results as a json object with the schema: current_value:string, new_value:string.
Do not include any unchanged values in your answer.
Do not include an explanation with your answer.
"""

skin_condition_name_sql = """select distinct skin_condition_name
                             from skincare_products_stg.skin_disease_picture
                             where skin_condition_name is not null
                             order by skin_condition_name"""

skin_disease_pictures_sql = """select *
                               from skincare_products_stg.skin_disease_picture
                               where skin_condition_name is not null"""

bq_client = bigquery.Client()

rows = bq_client.query(skin_condition_name_sql).result()

skin_condition_name_list = [row["skin_condition_name"] for row in rows]
skin_condition_name_str = '\n'.join(skin_condition_name_list)
print("skin_condition_name_str:", skin_condition_name_str)

vertexai.init(project=project_id, location=region)
model = GenerativeModel(model_name)

resp = model.generate_content([skin_condition_name_str, prompt])
resp_text = resp.text.replace("```json", "").replace("```", "").replace("\n", "")
print(resp_text)

skin_condition_mappings = json.loads(resp_text)
print("skin_condition_mappings:", skin_condition_mappings)

replacements = {}
for old, new in skin_condition_mappings.items():
    if old != new:
        replacements[old] = new
print("replacements:", replacements)

df = bq_client.query(skin_disease_pictures_sql).to_dataframe()
print("Original df:", df)

df["skin_condition_name"] = df["skin_condition_name"].map(replacements).fillna(df["skin_condition_name"])
print("Updated df:", df)

skin_condition_name_str: 11img017
11img018
11img019
14img010
1img011
1img015
3img006
4img005
4th_1img008
4th_disease
7img017
9img008
acanthosis_nigricans
accessory_nipple
accessory_trachus
acne
acne_closed_comedo
acne_cystic
acne_excoriated
acne_infantile
acne_keloidalis
acne_open_comedo
acne_pustular
acne_scar
acquired_digital_fibrokeratoma
acrocyanosis
acrodermatitis_enteropathica
actinic_cheilitis
actinic_cheilitis_sq_cell
actinic_cheilitis_sq_cell_lip
actinic_comedones
actinic_keratosis
actinic_keratosis_5fu
actinic_keratosis_horn
actinic_keratosis_pigmented
actinomycosis
acute_paronychia
aids
albinism
allergic_contact_dermatitis
alopecia_areata
amyloidosis
androgenic_alopecia
angioedema
angiokeratomas
angry_back_patch_testing
arsenical_keratoses
atopic_dermatitis
atopic_lichenification
atrophy_blanche
atypical_mycobacterium
atypical_nevi
axillary_granular_parakeratosis
basal_cell_carcinoma
basal_cell_carcinoma_lid
basal_cell_carcinoma_pigmented
basal_cell_carcinoma_sclerosing
basal_cell_carcinoma_superficial
basal_cell_nevus_syndrome
beaus_lines
becker_nevus
bed_ridges
benign_familial_chronic_pemphigus
biting_excoriation
biting_insects
black_heel
blue_nevus
blue_nevus_ota
botryomycosis_staph
bowen's_disease
bowens_disease
box6miscimg086_gp3
bullous_pemphigoid
cactus_granuloma
candida_axillae
candida_groin
candida_intertrigo
candida_penis
candidiasis
candidiasis_diaper
candidiasis_large_skin_folds
candidiasis_mouth
candidiasis_of_the_tongue
cat_bite
caterpillar_dermatitis
cellulitis
chapped_fissured_feet
cheilitis
cherry_angioma
chicken_pox
chigger_bites_bullous
chilblains_perniosis
child_0612051
cholinergic_urticaria
chondrodermatitis_nodularis
chronic_bullous_dermatosis_childhood
chronic_paronychia
clubbing
coccidiomycosis
cold_urticaria
collagenoma
colloid_milia
comedones_ears
confluent_reticulate_papillomatosis
congenital_anomalies
congenital_nevus
contact_dermatitis
coral_poisoning
corns
cosmetic_fragrance_allergy
cowden_disease
crest_syndrome
ctcl
cutaneous_horn
cutaneous_larva_migrans
cutaneous_t_cell_lymphoma
cylindroma
dariers_disease
degos_disease
dermagraphism
dermatitis
dermatitis_areola
dermatitis_arm
dermatitis_drug
dermatitis_herpetiformis
dermatitis_lids
dermatitis_swimming
dermatofibroma
dermatofibrosarcoma
dermatomyositis
dermatosis_papulosa_nigra
desquamation
desquamation_viral
diabetes_mellitus
diabetic_bullae
discoid_lupus
dissecting_cellulitis
distal_subungual_onychomycosis
drug_eruptions
dry_cracked_heels
dry_feet
duck_itch
dyshidrosis
ecthyma
eczema
eczema_acute
eczema_areola
eczema_areolae
eczema_arms
eczema_asteatotic
eczema_axillae
eczema_chronic
eczema_ears
eczema_fingertips
eczema_foot
eczema_hand
eczema_herpeticum
eczema_impetiginized
eczema_lids
eczema_nail
eczema_nummular
eczema_staph
eczema_subacute
eczema_trunk_generalized
eczema_vaccinatum
eczema_vulva
elastosis_perferans
elastosis_perforans
enterovirus_30
enterovirus_7
enterovirus_8
epidermal_cyst
epidermal_nevus
epidermodysplasia_verruciformis
epidermoid_cyst_ruptured
epidermolysis_bullosa
erosio_interdigitalis_blastomycetica
erysipelas
erysipeloid
erythema_ab_igne
erythema_annulare_centrifugum
erythema_dyschromium_perstans
erythema_elevatum_diutinum
erythema_infectiosum
erythema_multiforme
erythema_nodosum
erythema_toxicum_neonatorum
erythrasma
erythromelalgia
exfoliative_dermatitis
exostosis
extramammary_paget_disease
factitial_dermatitis
fiberglass_dermatitis
fibrofolliculoma
fibroma
fire_ants
fissure
fixed_drug_eruption
flea_bites
follicular_keratosis
folliculitis
folliculitis_decalvans
fordyce_spots
furuncles_carbuncles
genital_herpes_simplex
genital_ulcers
genital_warts
gianotti_crosti
glucagonoma
gonorrhea
granulation_tissue
granuloma_annulare
granuloma_faciale
grovers_disease
habit_tic_deformity
halo_nevus
hand_foot_and_mouth
hand_foot_and_mouth_disease
hand_foot_mouth_disease
hemangioma
hemangioma_infancy
henoch_schonlein_purpura
herpes
herpes_buttock
herpes_buttocks
herpes_cutaneous
herpes_gestationis
herpes_hand
herpes_simplex
herpes_type_1_primary
herpes_type_1_recurrent
herpes_type_2_primary
herpes_type_2_recurrent
herpes_zoster
hidradenitis_suppurativa
hirsutism
hives_urticaria_acute
hot_comb_alopecia
hot_tub_folliculitis
hydroa_aestivale
hydrocystoma
hyper_linear_crease
hyperhidrosis
hyperkeratosis
ichthosis
ichthyosis
ichthyosis_sex_linked
ichthyosis_vulgaris
icthyosis
id_reaction
idiopathic_guttate_hypomelanosis
impetigo
ingrown_nail
interstitial_granulomatous_dermatitis
intertrigo
iododerma
irritant_contact_dermatitis
jelly_fish_sting
kaposi_sarcoma
kawasaki_syndrome
keloids
keratoacanthoma
keratolysis_exfoliativa
keratosis
keratosis_pilaris
keratosis_punctata
kerion
koilonychia
kyrle_disease
leiomyomata
leishmaniasis
lentigo_adults
lentigo_maligna
leprosy
leukemia
leukonychia
leukoplakia
lichen_amyloidosis
lichen_myxedematosus
lichen_nitidus
lichen_planopilaris
lichen_planus
lichen_planus_drug
lichen_planus_hypertrophic
lichen_planus_oral
lichen_sclerosis_vulva
lichen_sclerosus
lichen_simplex_chronicus
lipoid_proteinosis
livido_reticularis
localized_pemphigoid
lupus_acute
lupus_chronic_cutaneous
lupus_subacute
lyme_disease
lymphangioma_circumscriptum
maceration
maculae_cerulea
majocchi_granuloma
malignant_melanoma
median_nail_dystrophy
melanocytic_nevi
melanoma_mimic
melanotic_macule
melasma
meningococcemia
merkel_cell_cancer
metal_dermatitis
metastasis
milia
milroy_disease
minocycline_pigmentation
mixed_connective_tissue_disease
molluscum_contagiosum
mongolian_spot
morphea
mucinosis
mucous_cyst
myiasis
myxedema
nail_distal_splitting
nail_melanoma
nail_ridging_and_beading
nail_ridging_beading
necrobiosis_lipoidica
neurofibromas
neurofibromatosis
neurofibromatosis_1
neurotic_excoriations
nevoxanthoendothelioma
nevus_anemicus
nevus_comedonicus
nevus_repigmented
nevus_sebaceous
nevus_spilus
normal_variations
north_american_blastomycosis
oil_spot_psoriasis
onychogryphosis
onycholysis
osler_node
otitis_externa
pachyonychia_congenita
paget_disease_breast
parasitosis_psychogenic
patch_testing
pearly_penile_papules
pediculosis_body
pediculosis_lids
pellagra
pemphigus
pemphigus_foliaceous
perioral_dermatitis
periorbital_edema
periungual_fibroma
periungual_wart
periungual_warts
perleche
phlebitis_superficial
phototoxic_reactions
phototoxic_reactions_doxycycline
piebaldism
pigmented_bands
pilar_cyst
pili_torti
pincer_nails
pinkus_tumor
pitted_keratolysis
pityriasis_alba
pityriasis_lichenoides
pityriasis_rosea
pityriasis_rubra_pilaris
pityrosporum_folliculitis
poikiloderma_civatte
polymorphous_light_eruption
pompholyx
porokeratosis
porphyrias
post-infectious_desquamation
post_inflammatory_hyperpigmentation
pressure_urticaria
pretibial_myxedema
proximal_subungual_onychomycosis
prurigo_nodularis
pseudo_cyst_auricle
pseudo_porphyria
pseudomonas
pseudomonas_cellulitis
pseudomonas_folliculitis
pseudomonas_infection
pseudopelade
pseudoxanthoma_elasticum
psoriasis
psoriasis_cellulitis
psoriasis_chronic_plaque
psoriasis_erythrodermic
psoriasis_guttate
psoriasis_inversus
psoriasis_nails
psoriasis_palms_soles
psoriasis_pustular_generalized
psoriasis_scalp
psoriasis_sunburn
pubic_lice
puppp
purpura_vomiting
pyoderma_gangrenosum
pyogenic_granuloma
raynaud_disease
reiter_syndrome
rheumatoid_nodule
rhinophyma
rhus_dermatitis
ridging_beading
rocky_mountain_spotted_fever
rosacea
rosacea_milia
rosacea_steroid
roseola_infantum
sarcoid
scabies
scarlet_fever
schamberg_disease
scleroderma
sea_bathers_eruption
seb_derm
seb_derm_lids
sebaceous_adenoma
sebaceous_glands
sebaceous_hyperplasia
sebaceous_keratosis
seborrheic_dermatitis
seborrheic_keratoses
seborrheic_keratosis
seborrheic_keratosis_irritated
sex-linked_ichthyosis
sex_linked_ichthyosis
shoe_allergy
skin_tags_polyps
small_pox
spider_angioma
spider_bite
splinter_hemorrhage
squamous_cell_carcinoma
squamous_cell_carcinoma_lip
squamous_cell_carcinoma_vulva
staphylococcal_folliculitis
stasis_dermatitis
steroid_perioral_dermatitis
stevens_johnson_syndrome
streptococci_anal_penis
stucco_keratoses
subungual_hematoma
sun_damaged_skin
superficial_phlebitis
sweets_syndrome
sycosis_barbae
syphilis
syringoma
systemically_induced_allergic_dermatitis
telangiectasias
telogen_effluvium
terry_nails
thrombosed_vein
tick_bite
tinea
tinea_amiantacea
tinea_beard
tinea_body
tinea_face
tinea_foot
tinea_foot_plantar
tinea_foot_webs
tinea_groin
tinea_hand
tinea_hand_dorsum
tinea_incognito
tinea_laboratory
tinea_manuum
tinea_palm
tinea_scalp
tinea_versicolor
trauma
trichofolliculoma
trichorrhexis_nodosa
trichotillomania
tuberous_sclerosis
tufted_folliculitis
twenty_nail_dystrophy
unilateral_telangiectasia
urticaria_vasculitis
varicella
vascular_anomaly
vascular_face
vasculitis
venous_lake
venous_malformations
verrucous_carcinoma
viral_exanthems
vitiligo
wart_common
wart_mouth
warts
warts_common
warts_cryotherapy
warts_digitate
warts_flat
warts_genital
warts_immunocompromised
warts_mouth
warts_oral
warts_periungual
warts_plantar
warts_treatment
weathering_nodules
white_superficial_onychomycosis
x_linked_ichthyosis
xanthomas
yellow_nails
{"acne_closed_comedo": "acne","acne_cystic": "acne","acne_excoriated": "acne","acne_infantile": "acne","acne_keloidalis": "acne","acne_open_comedo": "acne","acne_pustular": "acne","actinic_cheilitis_sq_cell": "actinic cheilitis","actinic_cheilitis_sq_cell_lip": "actinic cheilitis","bowens_disease": "bowen's disease","candida_axillae": "candidiasis","candida_groin": "candidiasis","candida_intertrigo": "candidiasis","candida_penis": "candidiasis","candidiasis_diaper": "candidiasis","candidiasis_large_skin_folds": "candidiasis","candidiasis_mouth": "candidiasis","candidiasis_of_the_tongue": "candidiasis","eczema_acute": "eczema","eczema_areola": "eczema","eczema_areolae": "eczema","eczema_arms": "eczema","eczema_asteatotic": "eczema","eczema_axillae": "eczema","eczema_chronic": "eczema","eczema_ears": "eczema","eczema_fingertips": "eczema","eczema_foot": "eczema","eczema_hand": "eczema","eczema_herpeticum": "eczema","eczema_impetiginized": "eczema","eczema_lids": "eczema","eczema_nail": "eczema","eczema_nummular": "eczema","eczema_staph": "eczema","eczema_subacute": "eczema","eczema_trunk_generalized": "eczema","eczema_vaccinatum": "eczema","eczema_vulva": "eczema","elastosis_perforans": "elastosis perferans","epidermoid_cyst_ruptured": "epidermoid cyst","genital_herpes_simplex": "genital herpes","genital_ulcers": "genital herpes","genital_warts": "warts","hand_foot_and_mouth": "hand, foot, and mouth disease","hand_foot_and_mouth_disease": "hand, foot, and mouth disease","herpes_buttock": "herpes","herpes_buttocks": "herpes","herpes_cutaneous": "herpes","herpes_gestationis": "herpes","herpes_hand": "herpes","herpes_simplex": "herpes","herpes_type_1_primary": "herpes","herpes_type_1_recurrent": "herpes","herpes_type_2_primary": "herpes","herpes_type_2_recurrent": "herpes","herpes_zoster": "herpes","hives_urticaria_acute": "urticaria","hot_tub_folliculitis": "folliculitis","ichthyosis": "ichthyosis vulgaris","icthyosis": "ichthyosis vulgaris","impetigo": "impetigo","keratosis": "keratosis pilaris","keratosis_pilaris": "keratosis pilaris","kerion": "tinea","lichen_planus_drug": "lichen planus","lichen_planus_hypertrophic": "lichen planus","lichen_planus_oral": "lichen planus","lupus_acute": "lupus","lupus_chronic_cutaneous": "lupus","lupus_subacute": "lupus","melanoma_mimic": "melanoma","nail_ridging_and_beading": "nail ridging","nail_ridging_beading": "nail ridging","pediculosis_body": "lice","pediculosis_lids": "lice","periungual_warts": "warts","pityriasis_alba": "pityriasis","pityriasis_lichenoides": "pityriasis","pityriasis_rosea": "pityriasis","pityriasis_rubra_pilaris": "pityriasis","pityrosporum_folliculitis": "folliculitis","psoriasis_cellulitis": "psoriasis","psoriasis_chronic_plaque": "psoriasis","psoriasis_erythrodermic": "psoriasis","psoriasis_guttate": "psoriasis","psoriasis_inversus": "psoriasis","psoriasis_nails": "psoriasis","psoriasis_palms_soles": "psoriasis","psoriasis_pustular_generalized": "psoriasis","psoriasis_scalp": "psoriasis","psoriasis_sunburn": "psoriasis","pubic_lice": "lice","rosacea": "rosacea","rosacea_milia": "rosacea","rosacea_steroid": "rosacea","seb_derm": "seborrheic dermatitis","seb_derm_lids": "seborrheic dermatitis","sebaceous_keratosis": "seborrheic keratosis","seborrheic_keratoses": "seborrheic keratosis","seborrheic_keratosis": "seborrheic keratosis","seborrheic_keratosis_irritated": "seborrheic keratosis","sex-linked_ichthyosis": "sex linked ichthyosis","sex_linked_ichthyosis": "sex linked ichthyosis","skin_tags_polyps": "skin tags","small_pox": "pox","squamous_cell_carcinoma_lip": "squamous cell carcinoma","squamous_cell_carcinoma_vulva": "squamous cell carcinoma","staphylococcal_folliculitis": "folliculitis","steroid_perioral_dermatitis": "perioral dermatitis","streptococci_anal_penis": "streptococcal infection","sun_damaged_skin": "sun damage","sycosis_barbae": "folliculitis","telangiectasias": "telangiectasia","tinea_amiantacea": "tinea","tinea_beard": "tinea","tinea_body": "tinea","tinea_face": "tinea","tinea_foot": "tinea","tinea_foot_plantar": "tinea","tinea_foot_webs": "tinea","tinea_groin": "tinea","tinea_hand": "tinea","tinea_hand_dorsum": "tinea","tinea_incognito": "tinea","tinea_laboratory": "tinea","tinea_manuum": "tinea","tinea_palm": "tinea","tinea_scalp": "tinea","tinea_versicolor": "tinea","warts_common": "warts","warts_cryotherapy": "warts","warts_digitate": "warts","warts_flat": "warts","warts_genital": "warts","warts_immunocompromised": "warts","warts_mouth": "warts","warts_oral": "warts","warts_periungual": "warts","warts_plantar": "warts","warts_treatment": "warts","white_superficial_onychomycosis": "onychomycosis","x_linked_ichthyosis": "sex linked ichthyosis"}
skin_condition_mappings: {'acne_closed_comedo': 'acne', 'acne_cystic': 'acne', 'acne_excoriated': 'acne', 'acne_infantile': 'acne', 'acne_keloidalis': 'acne', 'acne_open_comedo': 'acne', 'acne_pustular': 'acne', 'actinic_cheilitis_sq_cell': 'actinic cheilitis', 'actinic_cheilitis_sq_cell_lip': 'actinic cheilitis', 'bowens_disease': "bowen's disease", 'candida_axillae': 'candidiasis', 'candida_groin': 'candidiasis', 'candida_intertrigo': 'candidiasis', 'candida_penis': 'candidiasis', 'candidiasis_diaper': 'candidiasis', 'candidiasis_large_skin_folds': 'candidiasis', 'candidiasis_mouth': 'candidiasis', 'candidiasis_of_the_tongue': 'candidiasis', 'eczema_acute': 'eczema', 'eczema_areola': 'eczema', 'eczema_areolae': 'eczema', 'eczema_arms': 'eczema', 'eczema_asteatotic': 'eczema', 'eczema_axillae': 'eczema', 'eczema_chronic': 'eczema', 'eczema_ears': 'eczema', 'eczema_fingertips': 'eczema', 'eczema_foot': 'eczema', 'eczema_hand': 'eczema', 'eczema_herpeticum': 'eczema', 'eczema_impetiginized': 'eczema', 'eczema_lids': 'eczema', 'eczema_nail': 'eczema', 'eczema_nummular': 'eczema', 'eczema_staph': 'eczema', 'eczema_subacute': 'eczema', 'eczema_trunk_generalized': 'eczema', 'eczema_vaccinatum': 'eczema', 'eczema_vulva': 'eczema', 'elastosis_perforans': 'elastosis perferans', 'epidermoid_cyst_ruptured': 'epidermoid cyst', 'genital_herpes_simplex': 'genital herpes', 'genital_ulcers': 'genital herpes', 'genital_warts': 'warts', 'hand_foot_and_mouth': 'hand, foot, and mouth disease', 'hand_foot_and_mouth_disease': 'hand, foot, and mouth disease', 'herpes_buttock': 'herpes', 'herpes_buttocks': 'herpes', 'herpes_cutaneous': 'herpes', 'herpes_gestationis': 'herpes', 'herpes_hand': 'herpes', 'herpes_simplex': 'herpes', 'herpes_type_1_primary': 'herpes', 'herpes_type_1_recurrent': 'herpes', 'herpes_type_2_primary': 'herpes', 'herpes_type_2_recurrent': 'herpes', 'herpes_zoster': 'herpes', 'hives_urticaria_acute': 'urticaria', 'hot_tub_folliculitis': 'folliculitis', 'ichthyosis': 'ichthyosis vulgaris', 'icthyosis': 'ichthyosis vulgaris', 'impetigo': 'impetigo', 'keratosis': 'keratosis pilaris', 'keratosis_pilaris': 'keratosis pilaris', 'kerion': 'tinea', 'lichen_planus_drug': 'lichen planus', 'lichen_planus_hypertrophic': 'lichen planus', 'lichen_planus_oral': 'lichen planus', 'lupus_acute': 'lupus', 'lupus_chronic_cutaneous': 'lupus', 'lupus_subacute': 'lupus', 'melanoma_mimic': 'melanoma', 'nail_ridging_and_beading': 'nail ridging', 'nail_ridging_beading': 'nail ridging', 'pediculosis_body': 'lice', 'pediculosis_lids': 'lice', 'periungual_warts': 'warts', 'pityriasis_alba': 'pityriasis', 'pityriasis_lichenoides': 'pityriasis', 'pityriasis_rosea': 'pityriasis', 'pityriasis_rubra_pilaris': 'pityriasis', 'pityrosporum_folliculitis': 'folliculitis', 'psoriasis_cellulitis': 'psoriasis', 'psoriasis_chronic_plaque': 'psoriasis', 'psoriasis_erythrodermic': 'psoriasis', 'psoriasis_guttate': 'psoriasis', 'psoriasis_inversus': 'psoriasis', 'psoriasis_nails': 'psoriasis', 'psoriasis_palms_soles': 'psoriasis', 'psoriasis_pustular_generalized': 'psoriasis', 'psoriasis_scalp': 'psoriasis', 'psoriasis_sunburn': 'psoriasis', 'pubic_lice': 'lice', 'rosacea': 'rosacea', 'rosacea_milia': 'rosacea', 'rosacea_steroid': 'rosacea', 'seb_derm': 'seborrheic dermatitis', 'seb_derm_lids': 'seborrheic dermatitis', 'sebaceous_keratosis': 'seborrheic keratosis', 'seborrheic_keratoses': 'seborrheic keratosis', 'seborrheic_keratosis': 'seborrheic keratosis', 'seborrheic_keratosis_irritated': 'seborrheic keratosis', 'sex-linked_ichthyosis': 'sex linked ichthyosis', 'sex_linked_ichthyosis': 'sex linked ichthyosis', 'skin_tags_polyps': 'skin tags', 'small_pox': 'pox', 'squamous_cell_carcinoma_lip': 'squamous cell carcinoma', 'squamous_cell_carcinoma_vulva': 'squamous cell carcinoma', 'staphylococcal_folliculitis': 'folliculitis', 'steroid_perioral_dermatitis': 'perioral dermatitis', 'streptococci_anal_penis': 'streptococcal infection', 'sun_damaged_skin': 'sun damage', 'sycosis_barbae': 'folliculitis', 'telangiectasias': 'telangiectasia', 'tinea_amiantacea': 'tinea', 'tinea_beard': 'tinea', 'tinea_body': 'tinea', 'tinea_face': 'tinea', 'tinea_foot': 'tinea', 'tinea_foot_plantar': 'tinea', 'tinea_foot_webs': 'tinea', 'tinea_groin': 'tinea', 'tinea_hand': 'tinea', 'tinea_hand_dorsum': 'tinea', 'tinea_incognito': 'tinea', 'tinea_laboratory': 'tinea', 'tinea_manuum': 'tinea', 'tinea_palm': 'tinea', 'tinea_scalp': 'tinea', 'tinea_versicolor': 'tinea', 'warts_common': 'warts', 'warts_cryotherapy': 'warts', 'warts_digitate': 'warts', 'warts_flat': 'warts', 'warts_genital': 'warts', 'warts_immunocompromised': 'warts', 'warts_mouth': 'warts', 'warts_oral': 'warts', 'warts_periungual': 'warts', 'warts_plantar': 'warts', 'warts_treatment': 'warts', 'white_superficial_onychomycosis': 'onychomycosis', 'x_linked_ichthyosis': 'sex linked ichthyosis'}

##### Apply skin_condition_name standardization to staging table

In [102]:
import json
import pandas_gbq
import vertexai
from vertexai.generative_models import GenerativeModel, Part
from google.cloud import bigquery

project_id = "segfault-434120"
region = "us-central1"
model_name = "gemini-1.5-flash-001"
prompt = """
Go through this list of skin_condition_name values and look for values that have similar meanings but were given different names.
For example, 'rosacea', 'acne rosacea', and 'rosacea (acne)' could all be standardized to 'rosacea'.
Suggest a standard value, mapping the current one to the new one.
Return the list of original values along with their new values.
Format the results as a json object with the schema: current_value:string, new_value:string.
Do not include any unchanged values in your answer.
Do not include an explanation with your answer.
"""
skin_condition_name_sql = """select distinct skin_condition_name
                             from skincare_products_stg.skin_disease_picture
                             where skin_condition_name is not null
                             order by skin_condition_name"""

skin_disease_picture_sql = """select *
                               from skincare_products_stg.skin_disease_picture
                               where skin_condition_name is not null"""

bq_client = bigquery.Client()
rows = bq_client.query_and_wait(skin_condition_name_sql)

category_list = []
for row in rows:
    category_list.append(row["skin_condition_name"])
category_str = '\n'.join(category_list)

vertexai.init(project=project_id, location=region)
model = GenerativeModel(model_name)
resp = model.generate_content([category_str, prompt])
resp_text = resp.text.replace("```json", "").replace("```", "").replace("\n", "")
print(resp_text)
categories = json.loads(resp_text)
print(type(categories))

replacements = {} # will store the new categories

# categories can be either a dictionary or list type (depending on what LLM decides to do!)
if type(categories) == dict:
    for old, new in categories.items():
        if old == new:
            continue
        else:
            replacements[old] = new

if type(categories) == list:
    for cat_entry in categories:
        if cat_entry['current_category'] == cat_entry['new_category']:
            continue
        else:
            replacements[cat_entry['current_category']] = cat_entry['new_category']

print("replacements:", replacements)

df = bq_client.query_and_wait(skin_disease_picture_sql).to_dataframe()
print("orig df:", df)

df["skin_condition_name"] = df["skin_condition_name"].map(replacements).fillna(df["skin_condition_name"])
print("new df:", df)

table_id = "skincare_products_stg.skin_disease_picture"
pandas_gbq.to_gbq(df, table_id, project_id=project_id, if_exists="replace")

{"acne_closed_comedo": "acne","acne_cystic": "acne","acne_excoriated": "acne","acne_infantile": "acne","acne_keloidalis": "acne","acne_open_comedo": "acne","acne_pustular": "acne","actinic_cheilitis_sq_cell": "actinic cheilitis","actinic_cheilitis_sq_cell_lip": "actinic cheilitis","bowens_disease": "bowen's disease","candidiasis_diaper": "candidiasis","candidiasis_large_skin_folds": "candidiasis","candidiasis_mouth": "candidiasis","candidiasis_of_the_tongue": "candidiasis","chigger_bites_bullous": "chigger bites","dermatitis_areola": "eczema","dermatitis_arm": "eczema","dermatitis_drug": "eczema","dermatitis_herpetiformis": "eczema","dermatitis_lids": "eczema","dermatitis_swimming": "eczema","eczema_acute": "eczema","eczema_areola": "eczema","eczema_areolae": "eczema","eczema_arms": "eczema","eczema_asteatotic": "eczema","eczema_axillae": "eczema","eczema_chronic": "eczema","eczema_ears": "eczema","eczema_fingertips": "eczema","eczema_foot": "eczema","eczema_hand": "eczema","eczema_herpeticum": "eczema","eczema_impetiginized": "eczema","eczema_lids": "eczema","eczema_nail": "eczema","eczema_nummular": "eczema","eczema_staph": "eczema","eczema_subacute": "eczema","eczema_trunk_generalized": "eczema","eczema_vaccinatum": "eczema","eczema_vulva": "eczema","elastosis_perforans": "elastosis_perferans","enterovirus_30": "hand-foot-and-mouth disease","enterovirus_7": "hand-foot-and-mouth disease","enterovirus_8": "hand-foot-and-mouth disease","epidermoid_cyst_ruptured": "epidermoid cyst","genital_herpes_simplex": "herpes","genital_ulcers": "herpes","genital_warts": "warts","hand_foot_and_mouth": "hand-foot-and-mouth disease","hand_foot_and_mouth_disease": "hand-foot-and-mouth disease","herpes_buttock": "herpes","herpes_buttocks": "herpes","herpes_cutaneous": "herpes","herpes_gestationis": "herpes","herpes_hand": "herpes","herpes_simplex": "herpes","herpes_type_1_primary": "herpes","herpes_type_1_recurrent": "herpes","herpes_type_2_primary": "herpes","herpes_type_2_recurrent": "herpes","herpes_zoster": "herpes","hives_urticaria_acute": "urticaria","hot_comb_alopecia": "alopecia areata","keratosis": "keratosis pilaris","keratosis_pilaris": "keratosis pilaris","keratosis_punctata": "keratosis pilaris","lichen_planus_drug": "lichen planus","lichen_planus_hypertrophic": "lichen planus","lichen_planus_oral": "lichen planus","lichen_sclerosus": "lichen sclerosus et atrophicus","melanoma_mimic": "melanoma","nail_ridging_and_beading": "nail ridging","nail_ridging_beading": "nail ridging","periungual_warts": "warts","phototoxic_reactions_doxycycline": "phototoxic reaction","pityriasis_lichenoides": "pityriasis rosea","psoriasis_cellulitis": "psoriasis","psoriasis_chronic_plaque": "psoriasis","psoriasis_erythrodermic": "psoriasis","psoriasis_guttate": "psoriasis","psoriasis_inversus": "psoriasis","psoriasis_nails": "psoriasis","psoriasis_palms_soles": "psoriasis","psoriasis_pustular_generalized": "psoriasis","psoriasis_scalp": "psoriasis","psoriasis_sunburn": "psoriasis","pubic_lice": "lice","seb_derm": "seborrheic dermatitis","seb_derm_lids": "seborrheic dermatitis","seborrheic_dermatitis": "seborrheic dermatitis","seborrheic_keratoses": "seborrheic keratosis","seborrheic_keratosis": "seborrheic keratosis","seborrheic_keratosis_irritated": "seborrheic keratosis","sex-linked_ichthyosis": "ichthyosis","sex_linked_ichthyosis": "ichthyosis","skin_tags_polyps": "skin tags","squamous_cell_carcinoma_lip": "squamous cell carcinoma","squamous_cell_carcinoma_vulva": "squamous cell carcinoma","staphylococcal_folliculitis": "folliculitis","steroid_perioral_dermatitis": "perioral dermatitis","streptococci_anal_penis": "streptococcal infection","sun_damaged_skin": "photoaging","tinea_amiantacea": "tinea","tinea_beard": "tinea","tinea_body": "tinea","tinea_face": "tinea","tinea_foot": "tinea","tinea_foot_plantar": "tinea","tinea_foot_webs": "tinea","tinea_groin": "tinea","tinea_hand": "tinea","tinea_hand_dorsum": "tinea","tinea_incognito": "tinea","tinea_laboratory": "tinea","tinea_manuum": "tinea","tinea_palm": "tinea","tinea_scalp": "tinea","tinea_versicolor": "tinea","trichofolliculoma": "folliculitis","warts_common": "warts","warts_cryotherapy": "warts","warts_digitate": "warts","warts_flat": "warts","warts_genital": "warts","warts_immunocompromised": "warts","warts_mouth": "warts","warts_oral": "warts","warts_periungual": "warts","warts_plantar": "warts","warts_treatment": "warts","x_linked_ichthyosis": "ichthyosis"}
<class 'dict'>
replacements: {'acne_closed_comedo': 'acne', 'acne_cystic': 'acne', 'acne_excoriated': 'acne', 'acne_infantile': 'acne', 'acne_keloidalis': 'acne', 'acne_open_comedo': 'acne', 'acne_pustular': 'acne', 'actinic_cheilitis_sq_cell': 'actinic cheilitis', 'actinic_cheilitis_sq_cell_lip': 'actinic cheilitis', 'bowens_disease': "bowen's disease", 'candidiasis_diaper': 'candidiasis', 'candidiasis_large_skin_folds': 'candidiasis', 'candidiasis_mouth': 'candidiasis', 'candidiasis_of_the_tongue': 'candidiasis', 'chigger_bites_bullous': 'chigger bites', 'dermatitis_areola': 'eczema', 'dermatitis_arm': 'eczema', 'dermatitis_drug': 'eczema', 'dermatitis_herpetiformis': 'eczema', 'dermatitis_lids': 'eczema', 'dermatitis_swimming': 'eczema', 'eczema_acute': 'eczema', 'eczema_areola': 'eczema', 'eczema_areolae': 'eczema', 'eczema_arms': 'eczema', 'eczema_asteatotic': 'eczema', 'eczema_axillae': 'eczema', 'eczema_chronic': 'eczema', 'eczema_ears': 'eczema', 'eczema_fingertips': 'eczema', 'eczema_foot': 'eczema', 'eczema_hand': 'eczema', 'eczema_herpeticum': 'eczema', 'eczema_impetiginized': 'eczema', 'eczema_lids': 'eczema', 'eczema_nail': 'eczema', 'eczema_nummular': 'eczema', 'eczema_staph': 'eczema', 'eczema_subacute': 'eczema', 'eczema_trunk_generalized': 'eczema', 'eczema_vaccinatum': 'eczema', 'eczema_vulva': 'eczema', 'elastosis_perforans': 'elastosis_perferans', 'enterovirus_30': 'hand-foot-and-mouth disease', 'enterovirus_7': 'hand-foot-and-mouth disease', 'enterovirus_8': 'hand-foot-and-mouth disease', 'epidermoid_cyst_ruptured': 'epidermoid cyst', 'genital_herpes_simplex': 'herpes', 'genital_ulcers': 'herpes', 'genital_warts': 'warts', 'hand_foot_and_mouth': 'hand-foot-and-mouth disease', 'hand_foot_and_mouth_disease': 'hand-foot-and-mouth disease', 'herpes_buttock': 'herpes', 'herpes_buttocks': 'herpes', 'herpes_cutaneous': 'herpes', 'herpes_gestationis': 'herpes', 'herpes_hand': 'herpes', 'herpes_simplex': 'herpes', 'herpes_type_1_primary': 'herpes', 'herpes_type_1_recurrent': 'herpes', 'herpes_type_2_primary': 'herpes', 'herpes_type_2_recurrent': 'herpes', 'herpes_zoster': 'herpes', 'hives_urticaria_acute': 'urticaria', 'hot_comb_alopecia': 'alopecia areata', 'keratosis': 'keratosis pilaris', 'keratosis_pilaris': 'keratosis pilaris', 'keratosis_punctata': 'keratosis pilaris', 'lichen_planus_drug': 'lichen planus', 'lichen_planus_hypertrophic': 'lichen planus', 'lichen_planus_oral': 'lichen planus', 'lichen_sclerosus': 'lichen sclerosus et atrophicus', 'melanoma_mimic': 'melanoma', 'nail_ridging_and_beading': 'nail ridging', 'nail_ridging_beading': 'nail ridging', 'periungual_warts': 'warts', 'phototoxic_reactions_doxycycline': 'phototoxic reaction', 'pityriasis_lichenoides': 'pityriasis rosea', 'psoriasis_cellulitis': 'psoriasis', 'psoriasis_chronic_plaque': 'psoriasis', 'psoriasis_erythrodermic': 'psoriasis', 'psoriasis_guttate': 'psoriasis', 'psoriasis_inversus': 'psoriasis', 'psoriasis_nails': 'psoriasis', 'psoriasis_palms_soles': 'psoriasis', 'psoriasis_pustular_generalized': 'psoriasis', 'psoriasis_scalp': 'psoriasis', 'psoriasis_sunburn': 'psoriasis', 'pubic_lice': 'lice', 'seb_derm': 'seborrheic dermatitis', 'seb_derm_lids': 'seborrheic dermatitis', 'seborrheic_dermatitis': 'seborrheic dermatitis', 'seborrheic_keratoses': 'seborrheic keratosis', 'seborrheic_keratosis': 'seborrheic keratosis', 'seborrheic_keratosis_irritated': 'seborrheic keratosis', 'sex-linked_ichthyosis': 'ichthyosis', 'sex_linked_ichthyosis': 'ichthyosis', 'skin_tags_polyps': 'skin tags', 'squamous_cell_carcinoma_lip': 'squamous cell carcinoma', 'squamous_cell_carcinoma_vulva': 'squamous cell carcinoma', 'staphylococcal_folliculitis': 'folliculitis', 'steroid_perioral_dermatitis': 'perioral dermatitis', 'streptococci_anal_penis': 'streptococcal infection', 'sun_damaged_skin': 'photoaging', 'tinea_amiantacea': 'tinea', 'tinea_beard': 'tinea', 'tinea_body': 'tinea', 'tinea_face': 'tinea', 'tinea_foot': 'tinea', 'tinea_foot_plantar': 'tinea', 'tinea_foot_webs': 'tinea', 'tinea_groin': 'tinea', 'tinea_hand': 'tinea', 'tinea_hand_dorsum': 'tinea', 'tinea_incognito': 'tinea', 'tinea_laboratory': 'tinea', 'tinea_manuum': 'tinea', 'tinea_palm': 'tinea', 'tinea_scalp': 'tinea', 'tinea_versicolor': 'tinea', 'trichofolliculoma': 'folliculitis', 'warts_common': 'warts', 'warts_cryotherapy': 'warts', 'warts_digitate': 'warts', 'warts_flat': 'warts', 'warts_genital': 'warts', 'warts_immunocompromised': 'warts', 'warts_mouth': 'warts', 'warts_oral': 'warts', 'warts_periungual': 'warts', 'warts_plantar': 'warts', 'warts_treatment': 'warts', 'x_linked_ichthyosis': 'ichthyosis'}
orig df:                  skin_condition_name affected_skin_color  severity  \
0                 contact_dermatitis                null      null
1                          fire_ants                null      null
2                        spider_bite                null      null
3                      patch_testing               light      null
4                      patch_testing               light      null
...                              ...                 ...       ...
3813  distal_subungual_onychomycosis              yellow  moderate
3814  distal_subungual_onychomycosis               brown  moderate
3815  distal_subungual_onychomycosis               brown  moderate
3816  distal_subungual_onychomycosis              yellow  moderate
3817  distal_subungual_onychomycosis              yellow  moderate

                                             image_link          _data_source  \
0     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
1     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
2     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
4     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
...                                                 ...                   ...
3813  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3814  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3815  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3816  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3817  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture

                           _load_time
0    2024-09-25 02:15:36.624486+00:00
1    2024-09-25 02:15:36.624486+00:00
2    2024-09-25 02:15:36.624486+00:00
3    2024-09-25 02:15:36.624486+00:00
4    2024-09-25 02:15:36.624486+00:00
...                               ...
3813 2024-09-25 02:15:36.624486+00:00
3814 2024-09-25 02:15:36.624486+00:00
3815 2024-09-25 02:15:36.624486+00:00
3816 2024-09-25 02:15:36.624486+00:00
3817 2024-09-25 02:15:36.624486+00:00

[3818 rows x 6 columns]
new df:                  skin_condition_name affected_skin_color  severity  \
0                 contact_dermatitis                null      null
1                          fire_ants                null      null
2                        spider_bite                null      null
3                      patch_testing               light      null
4                      patch_testing               light      null
...                              ...                 ...       ...
3813  distal_subungual_onychomycosis              yellow  moderate
3814  distal_subungual_onychomycosis               brown  moderate
3815  distal_subungual_onychomycosis               brown  moderate
3816  distal_subungual_onychomycosis              yellow  moderate
3817  distal_subungual_onychomycosis              yellow  moderate

                                             image_link          _data_source  \
0     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
1     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
2     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
4     https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
...                                                 ...                   ...
3813  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3814  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3815  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3816  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture
3817  https://storage.cloud.google.com/skincare-prod...  skin_disease_picture

                           _load_time
0    2024-09-25 02:15:36.624486+00:00
1    2024-09-25 02:15:36.624486+00:00
2    2024-09-25 02:15:36.624486+00:00
3    2024-09-25 02:15:36.624486+00:00
4    2024-09-25 02:15:36.624486+00:00
...                               ...
3813 2024-09-25 02:15:36.624486+00:00
3814 2024-09-25 02:15:36.624486+00:00
3815 2024-09-25 02:15:36.624486+00:00
3816 2024-09-25 02:15:36.624486+00:00
3817 2024-09-25 02:15:36.624486+00:00

[3818 rows x 6 columns]

100%|██████████| 1/1 [00:00<00:00, 7681.88it/s]